# Copyright Â© 2024. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.

enabled: true
# TIBCO PLATFORM OVERLAY
global:
  enableLogging: true
  cp:
    enableResourceConstraints: true
    data:
      CP_DB_CONFIGURATION: provider-cp-database-config
  tibco:
    image_name:
      cpScripts: "core-cp-scripts"
  external:
    db_ssl_mode: ""
  # Pod Security Context configuration
  # This configuration ensures that the pod is run with non-root privileges for enhanced security.
  # The user, group, and filesystem group IDs are all set to 1000.
  # The filesystem group change policy is set to "Always", meaning the filesystem group is always set to the fsGroup.
  # The seccomp (secure computing mode) profile is set to RuntimeDefault, which means it uses the default profile provided by the runtime.
  # The sysctls configuration allows the platform hybrid proxy to bind to low ports (below 1024) as a non-root user.
  # This is achieved by setting the 'net.ipv4.ip_unprivileged_port_start' sysctl to 0.
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    fsGroupChangePolicy: "Always"
    seccompProfile:
      type: RuntimeDefault

  containerSecurityContext:
    # It specifies that privilege escalation is not allowed for security reasons.
    # Additionally, it drops all capabilities, which is a common security practice to minimize potential risks.
    querynode:
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - CAP_NET_RAW
          - ALL

querynode:
  # The number of successive failed probes before indicating readiness failure.
  readinessFailureThreshold: 10

  # The initial delay for readiness probes in seconds.
  readinessInitialDelaySeconds: 12

  # The period between readiness probes.
  readinessPeriodSeconds: 15

  # The timeout for readiness probes.
  readinessTimeoutSeconds: 10

  # The number of successive  probes before indicating readiness success.
  readinessSuccessThreshold: 1

  # The number of successive failed probes before indicating livess failure.
  livenessFailureThreshold: 10

  # The initial delay for liveness probes in seconds.
  livenessInitialDelaySeconds: 15

  # The period between liveness probes.
  livenessPeriodSeconds: 15

  # The timeout for liveness probes.
  livenessTimeoutSeconds: 10

  # The number of successive failed probes before indicating lives success.
  livenessSuccessThreshold: 1

# Resource values for production like setup
resources:
  requests:
    cpu: 200m
    memory: 1024Mi
  limits:
    cpu: 500m
    memory: 2048Mi

# Configure Heap size and other java options
javaOptions: "-Xms1g -Xmx2g"

## Images
##
## Control what image to use
images:
  querynode:
    repository:
    image:
      name: hawk-querynode
      pullPolicy: IfNotPresent
      # tag: 134
      tag: "1.14.0.4"

# no of replicas
replicaCount: "1"
