apiVersion: v2
appVersion: 1.1.0
description: TIBCO Platform Finops -- Monitoring
home: https://github.com/tibco/tp-dp-monitor-agent
icon: https://pbs.twimg.com/profile_images/1064638558110007296/K6HqaXwh_400x400.jpg
maintainers:
- email: cdash-dev@tibco.com
  name: TIBCO FINOPS Dev Team
name: tp-dp-monitor-agent
version: 1.1.94
