#
# Copyright (c) 2023-2024. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#

{{-  $emsParams := include "need.msg.ems.params" . | fromYaml -}}
{{ if ne "none" ( $emsParams.ems.pvcShareName | default "none" ) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ $emsParams.ems.pvcShareName }}"
  labels:
    {{ include "ems.std.labels" $emsParams | indent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "{{ $emsParams.ems.pvcShareSize }}"
  storageClassName: "{{ $emsParams.dp.scSharedName }}"
{{ end }}
