{{ if .Values.ems.opsEnable }}
#
# Copyright (c) 2023-2024. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#

#   ${hostname}-${replicaId}.${serviceName}.${namespace}.svc.${clusterDomain}
#
#
# HELPER VARIABLE DEFINITIONS
{{-  $emsParams := include "need.msg.ems.params" . | fromYaml -}}
{{-  $emsNeedsVct := "no" -}}
{{- if ne "ftl" $emsParams.ems.stores -}}
  {{- fail "Unsupported Store type" -}}
{{- end -}}
{{- $stsname := printf "%s-ops" $emsParams.ems.name -}}
{{- $svcname := printf "%s-%s" $emsParams.ems.name "ems" -}}
{{- $svcFtl := printf "%s-%s" $emsParams.ems.name "ftl" -}}
{{- $svcFtlHost := printf "%s.%s.svc" $svcFtl .Release.Namespace -}}
{{- $svcEms := printf "%s-%s" $emsParams.ems.name "ems" -}}
{{- $svcEmsHost := printf "%s.%s.svc" $svcEms .Release.Namespace -}}
{{- $svcEmsActiveHost := printf "%sactive.%s.svc" $svcEms .Release.Namespace -}}
{{- $dataPvc := $emsParams.ems.logs.storageName -}}
#
kind: StatefulSet
apiVersion: apps/v1
metadata:
    name: "{{ $stsname }}"
    namespace: "{{ .Release.Namespace }}"
    labels:
      {{ include "msg.dp.labels" . | indent 6 }}
      name: "{{ $stsname }}"
      # Optional and Instance specific services are not currently supported
      # by the CAP-DB or Health monitoring
      # app.kubernetes.io/name: "{{ $stsname }}"
      app: msg-ems-ftl
      tib-dp-name: "{{ $emsParams.dp.name }}"
      tib-dp-app: msg-ems-ftl
      tib-msg-stsname: "{{ $stsname }}"
      tib-msg-ems-name: "{{ $emsParams.ems.name }}"
      tib-msg-ems-sizing: "{{ $emsParams.ems.sizing }}"
      tib-msg-ems-use: "{{ $emsParams.ems.use }}"
      sidecar.istio.io/inject: "{{ $emsParams.ems.istioEnable }}"
    annotations:
      {{ include "msg.dp.mon.annotations" . | indent 6 }}
      platform.tibco.com/quorum-strategy: "active-active"
      platform.tibco.com/quorum-min: "1"
spec:
    podManagementPolicy: Parallel
    replicas: 1
    selector:
        matchLabels:
          tib-msg-stsname: "{{ $stsname }}"
          tib-dp-release: "{{ .Release.Name }}"
    serviceName: "{{ $stsname }}"
    template:
        metadata:
            labels:
                tib-dp-name: "{{ $emsParams.dp.name }}"
                {{ include "msg.dp.labels" . | indent 16 }}
                {{ include "msg.dp.net.kubectl" . | indent 16}}
                tib-msg-stsname: "{{ $stsname }}"
                component: ems-ops
                app: msg-ems-ftl
                tib-msg-ems-name: "{{ $emsParams.ems.name }}"
                tib-msg-ems-sizing: "{{ $emsParams.ems.sizing }}"
                tib-msg-ems-use: "{{ $emsParams.ems.use }}"
                "sidecar.istio.io/inject": "{{ $emsParams.ems.istioEnable }}"
            name: ems-ops
            annotations:
              cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
        spec:
            {{- if ne "none" $emsParams.dp.pullSecret }}
            imagePullSecrets:
            - name: {{ $emsParams.dp.pullSecret }}
            {{- end }}
            # NOTE: if hostname/subdomain do not agree with podname/service
            # .. DNS pod resolution problems can occur
            hostname: "{{ $stsname }}"
            enableServiceLinks: false
            subdomain: "{{ $stsname }}"
            nodeSelector:
              kubernetes.io/os: linux
            containers:
            - name: "{{ $stsname }}"
              image: "{{ $emsParams.ops.image }}"
              imagePullPolicy: "{{ $emsParams.dp.pullPolicy }}"
              resources:
                requests:
                  memory: "0.5Gi"
                  cpu: "0.1"
                limits:
                  memory: "8Gi"
                  cpu: "4"
              # exec /usr/local/watchdog/bin/wait-for-shutdown.sh  ; 
              command: ['bash', '-c' ]
              args:
              - >
                ( mkdir -p /data/boot ; cd /data/boot ;
                    for x in /boot/mk-*.sh ; do bash < $x ; done | tee boot.out ) ;
                exec wait-for-shutdown.sh  ; 
              volumeMounts:
              - mountPath: /boot
                name: scripts-vol
              - mountPath: /config
                name: params-vol
              - mountPath: /logs
                  {{ if eq "sharedPvc" $emsParams.ems.logs.storageType }}
                name: "ems-share"
                subPathExpr: "$(MY_RELEASE)/logs"
                  {{ else }}
                name: "ems-log"
                  {{ end }}
              {{ $shareName := "none" }}
                {{ if eq "sharedPvc" $emsParams.ems.msgData.storageType }}
                  {{ $shareName = $emsParams.ems.msgData.storageName }}
                {{ end }}
                {{ if eq "sharedPvc" $emsParams.ems.logs.storageType }}
                  {{ $shareName = $emsParams.ems.logs.storageName }}
                {{ end }}
                {{ if ne "none" ( $emsParams.ems.pvcShareName | default "none" ) }}
                  {{ $shareName = $emsParams.ems.pvcShareName }}
                {{ end }}
              {{ if ne "none" $shareName }}
              - mountPath: /share
                name: "ems-share"
              {{ end }}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              env:
              {{ include "msg.envStdPodRefs" . | indent  14 }}
              - name: ACCEPT_EUA
                value: "y"
              - name: GOTRACEBACK
                value: "crash"
              - name: TCM_WATCHDOG_TYPE
                value: candidate
              - name: TCM_WATCHDOG_LOG_FILE
                value: /logs/$(MY_POD_NAME)/watchdog.log
              - name: MY_RELEASE
                value: "{{ .Release.Name }}"
              - name: REALM_PORT
                value: "{{ $emsParams.ems.ports.realmPort }}"
              - name: EMS_TCP_PORT
                value: "{{ $emsParams.ems.ports.tcpPort }}"
              - name: EMS_INIT_JSON
                value: "/data/boot/tibemsd-ftl.json"
              - name: EMS_HTTP_PORT
                value: "{{ $emsParams.ems.ports.httpPort }}"
              - name: EMS_SERVICE
                value: "{{ $emsParams.ems.name }}-ems"
              - name: MY_SVC_NAME
                value: "{{ $stsname }}"
              - name: MY_SVC_HOST
                value: "$(MY_POD_NAME).{{ $stsname }}.{{ .Release.Namespace }}.svc"
              - name: FTL_REALM_URL
                # the service load-balanced REALM URL
                value: "http://{{ $svcFtlHost }}:$(REALM_PORT)"
              - name: EMS_TCP_URL
                # the service load-balanced EMS TCP URL
                value: "tcp://{{ $svcEmsActiveHost }}:$(EMS_TCP_PORT),tcp://{{ $svcEmsHost }}:$(EMS_TCP_PORT)"
              - name: EMS_SSL_URL
                # the service load-balanced EMS SSL URL
                value: "ssl://{{ $svcEmsActiveHost }}:$(EMS_SSL_PORT),ssl://{{ $svcEmsHost }}:$(EMS_SSL_PORT)"
              - name: TCM_WATCHDOG_CONFIG
                value: "/data/boot/watchdog.yml"
              - name: TCM_WD_PORT
                value: "{{ $emsParams.ems.ports.watchdogPort }}"
              - name: TCM_WATCHDOG_HOSTPORT
                value: "$(MY_POD_NAME):$(TCM_WD_PORT)"
              #- name: TIB_RS_CURL_VERBOSE
              #  value: "1"
            volumes:
            - name: scripts-vol
              configMap:
                name: "{{ $emsParams.ems.name }}-scripts"
            - name: params-vol
              configMap:
                name: "{{ $emsParams.ems.name }}-params"
            {{ if ne "none" $shareName }}
            - name: "ems-share"
              persistentVolumeClaim:
                claimName: "{{ $shareName }}"
            {{ end }}
            {{ if ne "sharedPvc" $emsParams.ems.logs.storageType }}
            - name: "ems-log"
              emptyDir: {}
            {{ end }}
            dnsPolicy: ClusterFirst
            restartPolicy: Always
            schedulerName: default-scheduler
            securityContext:
              # user=emsaqa, group=msgsrc
              runAsUser: {{ int $emsParams.dp.uid }}
              runAsGroup: {{ int $emsParams.dp.gid }}
              fsGroup: {{ int $emsParams.dp.gid }}
            # The service account allows access to helm/kubectl actions
            serviceAccountName: "{{ $emsParams.dp.serviceAccount }}"
            terminationGracePeriodSeconds: 10
    updateStrategy:
        # type: OnDelete
...
{{- end -}}
