#
# Copyright Â© 2023 - 2025. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#

apiVersion: v2
name: platform-base
description: TIBCO Platform base chart
type: application
version: 1.6.0-alpha.91
appVersion: "1.6.0"
keywords:
  - tibco-platform
  - platform
  - base
annotations:
  app.helm.sh/component: control-plane
  app.helm.sh/name: platform-base
dependencies:
  - name: tp-cp-configuration
    version: "1.6.0"
    repository: alias:tibco-platform
  - name: tp-cp-recipes
    version: "1.6.31"
    repository: alias:tibco-platform
  - name: tp-cp-o11y
    version: "1.6.3"
    repository: alias:tibco-platform
  - name: tp-cp-core
    version: "1.6.36"
    repository: alias:tibco-platform
  - name: tp-cp-core-ops
    version: "1.6.36"
    repository: alias:tibco-platform
  - name: tp-cp-core-finops
    version: "1.6.555"
    repository: alias:tibco-platform
  - name: tp-cp-integration
    version: "1.6.24"
    repository: alias:tibco-platform
    condition: tp-cp-integration.enabled
    tags:
      - integration
  - name: tp-cp-tibcohub-contrib
    version: "1.6.6"
    repository: alias:tibco-platform
    condition: tp-cp-tibcohub-contrib.enabled
  - name: tp-cp-msg-contrib
    version: "1.6.12"
    repository: alias:tibco-platform
    condition: tp-cp-msg-contrib.enabled
  - name: tp-cp-msg-recipes
    version: "1.6.12"
    repository: alias:tibco-platform
    condition: tp-cp-msg-recipes.enabled
  - name: tp-cp-hawk
    version: "1.6.12"
    repository: alias:tibco-platform
    condition: tp-cp-hawk.enabled
  - name: tp-cp-cli
    version: "0.9.23"
    repository: alias:tibco-platform
