#
# Copyright Â© 2023 - 2025. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#

apiVersion: v2
name: platform-base
description: TIBCO Platform base chart
type: application
version: 1.9.0-alpha.103
appVersion: "1.9.0"
keywords:
  - tibco-platform
  - platform
  - base
annotations:
  app.helm.sh/component: control-plane
  app.helm.sh/name: platform-base
dependencies:
  - name: tp-cp-o11y
    version: "1.9.*"
    condition: tp-cp-o11y.enabled
  - name: tp-cp-configuration
    version: "1.9.*"
  - name: tp-cp-recipes
    version: "1.9.19"
    repository: alias:tibco-platform
  - name: tp-cp-core
    version: "1.9.*"
  - name: tp-cp-core-ops
    version: "1.9.*"
  - name: tp-cp-core-finops
    version: "1.9.576"
  - name: tp-cp-integration
    version: "1.9.25"
    repository: alias:tibco-platform
    condition: tp-cp-integration.enabled
    tags:
      - integration
  - name: tp-cp-tibcohub-contrib
    version: "1.8.4"
    repository: alias:tibco-platform
    condition: tp-cp-tibcohub-contrib.enabled
  - name: tp-cp-msg-contrib
    version: "1.9.28"
    repository: alias:tibco-platform
    condition: tp-cp-msg-contrib.enabled
  - name: tp-cp-msg-recipes
    version: "1.9.28"
    repository: alias:tibco-platform
    condition: tp-cp-msg-recipes.enabled
  - name: tp-cp-hawk
    version: "1.9.28"
    repository: alias:tibco-platform
    condition: tp-cp-hawk.enabled
  - name: tp-cp-hawk-console-recipes
    version: "1.9.28"
    repository: alias:tibco-platform
    condition: tp-cp-hawk-recipes.enabled
  - name: tp-cp-cli
    version: "1.0.0"
  - name: tp-cp-alertmanager
    version: "1.9.*"
  - name: tp-cp-alerts-service
    version: "1.9.*"
  - name: tp-cp-prometheus
    version: "1.9.8"
  - name: dp-oauth2proxy-recipes
    version: "1.9.*"
