# Copyright Â© 2025. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.

# TIBCO Route definition; this is where you define your microservice endpoints
apiVersion: cloud.tibco.com/v1
kind: TibcoRoute
metadata:
  name: tp-cp-bw5ce-webserver
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bw-webserver.shared.labels.standard" . | nindent 4 }}
spec:
  serviceName: tp-cp-bw5ce-webserver
  env:
    - name: TSC_DNS_DOMAIN
      valueFrom:
        configMapKeyRef:
          name: {{ include "tp-control-plane-dnsdomain-configmap" . }}
          key: TSC_DNS_DOMAIN
  endpoints:
    - path: /cp/bw5ce/web-ui-content
      internalPath: /
      port: 3003
      protocol: http
      proxies:
        - listener: virtual
          config: secure
          fqdn: "${TSC_DNS_DOMAIN}"
          methods:
            - GET
          configVariables:
            SECURE_REDIRECT_SKIP_ACCTS_CHECK: "true"
            SECURE_REDIRECT_SKIP_EULA_CHECK: "true"
            SECURE_REDIRECT_SKIP_ORG_CHECK: "true"
          enableRedirects: true
          allowClientCache: true
          allowXFrameOptions: false
    - path: /cp/bw5ce/v1
      internalPath: /tp-cp-bw5ce-ws/v1
      port: 3003
      protocol: http
      proxies:
        - listener: virtual
          config: secure
          fqdn: "${TSC_DNS_DOMAIN}"
          configVariables:
            SECURE_REDIRECT_SKIP_ACCTS_CHECK: "true"
            SECURE_REDIRECT_SKIP_EULA_CHECK: "true"
            SECURE_REDIRECT_SKIP_ORG_CHECK: "true"
          allowClientCache: false
          allowXFrameOptions: false
          enableRedirects: false
    - path: /cp/v1/contributors/bw5ce/bw5ce-cp-config.json
      internalPath: /bw5ce-cp-config.json
      port: 3003
      protocol: http
      proxies:
        - listener: virtual
          config: secure
          fqdn: "${TSC_DNS_DOMAIN}"
          configVariables:
            SECURE_REDIRECT_SKIP_ACCTS_CHECK: "true"
            SECURE_REDIRECT_SKIP_EULA_CHECK: "true"
            SECURE_REDIRECT_SKIP_ORG_CHECK: "true"
          allowClientCache: false
          allowXFrameOptions: false
          enableRedirects: false
    - internalPath: /cp/bw5ce-api/v1
      path: /cp/bw5ce-api/v1
      port: 3003
      protocol: http
      proxies:
        - allowClientCache: true
          allowXFrameOptions: false
          config: secure
          configVariables:
            SECURE_REDIRECT_SKIP_ACCTS_CHECK: "true"
            SECURE_REDIRECT_SKIP_EULA_CHECK: "true"
            SECURE_REDIRECT_SKIP_ORG_CHECK: "true"
          enableRedirects: true
          fqdn: ${TSC_DNS_DOMAIN}
          listener: virtual
    - path: /cp/bw5ce/bw5ce-alerts/main.js
      internalPath: /bw5ce-alerts/main.js
      port: 3003
      protocol: http
      proxies:
        - listener: virtual
          config: secure
          fqdn: "${TSC_DNS_DOMAIN}"
          configVariables:
            SECURE_REDIRECT_SKIP_ACCTS_CHECK: "true"
            SECURE_REDIRECT_SKIP_EULA_CHECK: "true"
            SECURE_REDIRECT_SKIP_ORG_CHECK: "true"
          allowClientCache: true
          allowXFrameOptions: false
          enableRedirects: true
          methods:
            - GET
    - path: /cp/bw5ce/bw5ce-alerts-preview/main.js
      internalPath: /bw5ce-alerts-preview/main.js
      port: 3003
      protocol: http
      proxies:
        - listener: virtual
          config: secure
          fqdn: "${TSC_DNS_DOMAIN}"
          configVariables:
            SECURE_REDIRECT_SKIP_ACCTS_CHECK: "true"
            SECURE_REDIRECT_SKIP_EULA_CHECK: "true"
            SECURE_REDIRECT_SKIP_ORG_CHECK: "true"
          allowClientCache: true
          allowXFrameOptions: false
          enableRedirects: true
          methods:
            - GET
