{{/*
    Copyright Â© 2025. Cloud Software Group, Inc.
    This file is subject to the license terms contained
    in the license file that is distributed with this file.
*/}}

{{- if .Values.rbac.ems -}}
{{- if .Values.global.tibco.enableClusterScopedPerm -}}
{{- if eq .Release.Namespace .Values.global.tibco.primaryNamespaceName -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "dp-configure-namespace.dataPlaneId" . }}-ems-cluster-scope
  labels:
    {{- include "dp-configure-namespace.labels" . | nindent 4 }}
    platform.tibco.com/aggregate-to-cluster-role: "{{ include "dp-configure-namespace.dataPlaneId" . }}"
rules: 
- apiGroups: [""]
  resources: ["nodes", "persistentvolume"]
  verbs: ["get"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["get"]
{{- end -}}
{{- end }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "dp-configure-namespace.dataPlaneId" . }}-ems
  labels:
    {{- include "dp-configure-namespace.labels" . | nindent 4 }}
rules: 
- apiGroups: [""]
  resources: ["secrets", "pods", "persistentvolumeclaims", "configmaps", "services"]
  verbs: ["list", "watch", "create", "get", "update", "delete", "patch"]
- apiGroups: ["apps"]
  resources: ["statefulsets", "statefulsets/scale"]
  verbs: ["list", "watch", "create", "get", "update", "delete", "patch"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["list", "watch", "create", "get", "update", "delete", "patch"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs:     ["get", "list", "watch", "create", "update", "delete", "patch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs:     ["get", "list", "watch", "create", "update", "delete", "patch"]
- apiGroups: ["policy"]
  resources: ["poddisruptionbudgets"]
  verbs: ["list", "watch", "create", "get", "update", "delete", "patch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "dp-configure-namespace.dataPlaneId" . }}-ems
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "dp-configure-namespace.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "dp-configure-namespace.dataPlaneId" . }}-ems
subjects:
- kind: ServiceAccount
  name: {{ include "dp-configure-namespace.serviceAccount" . | quote }}
  namespace: {{ include "dp-configure-namespace.primaryNamespaceName" . | quote }}

{{- end -}}
