apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: prometheus-strip-prefix
  namespace: prometheus
spec:
  stripPrefix:
    prefixes:
      - /o11y/metrics-server
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik-prometheus
  namespace: prometheus
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: prometheus-prometheus-strip-prefix@kubernetescrd
spec:
  ingressClassName: %%REPLACE_WITH_YOUR_INGRESS_CLASS_NAME%%
  rules:
  - host: %%REPLACE_ME_WITH_MACHINE_HOST_NAME%%
    http:
      paths:
      - path: /o11y/metrics-server
        pathType: Prefix
        backend:
          service:
            name: prometheus-server
            port:
              number: 80
