# Copyright Â© 2025. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#
apiVersion: v2
name: flogo-utilities
version: "1.14.0"
appVersion: "1.14.0"
description: Flogo buildtype, connectors and VSCode extension
