# Copyright Â© 2025. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.

global:
  tibco:
    containerRegistry:
      url: ""
      username: ""
      password: ""
      repository: ""
      imagePullSecretName: ""
      customCertSecret: ""
    controlPlaneInstanceId: ""
    enableResourceConstraints: true
    useSingleNamespace: true
    serviceAccount: ""
    # The fluentbit configuration section.
    # It specifies that the fluentbit should not run as a non-root user and the user ID should be 0 (root).
    # Privilege escalation is not allowed for security reasons.
    # Additionally, it drops all capabilities, which is a common security practice to minimize potential risks.
    # GitHub issue: https://github.com/fluent/fluent-bit/issues/872#issuecomment-827763207, https://github.com/kyma-project/kyma/pull/11657/files
    logging:
      fluentbit:
        enabled: true
        image:
          name: "common-fluentbit"
          registry: ""
          repo: ""
          tag: 4.1.0
          pullPolicy: IfNotPresent
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
    proxy:
      http: ""
      https: ""
      noproxy: ""
  external:
    storage:
      pvcName: "control-plane-pvc"

image:
  name: infra-container-image-extractor
  registry: ""
  repo: ""
  tag: 170-distroless
  pullPolicy: IfNotPresent

debug:
  image:
    name: common-distroless-base-debian-debug
    tag: 12.12

nameOverride: ""
podAnnotations: {}

# Pod Security Context configuration
# This configuration ensures that the pod is run with non-root privileges for enhanced security.
# The user, group, and filesystem group IDs are all set to 1000.
# The filesystem group change policy is set to "Always", meaning the filesystem group is always set to the fsGroup.
# The seccomp (secure computing mode) profile is set to RuntimeDefault, which means it uses the default profile provided by the runtime.
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  fsGroupChangePolicy: "Always"
  seccompProfile:
    type: RuntimeDefault

securityContext:
  # It specifies that privilege escalation is not allowed for security reasons.
  # Additionally, it drops all capabilities, which is a common security practice to minimize potential risks.
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL
      - CAP_NET_RAW

scripts:
  resources:
    requests:
      cpu: 50m
      memory: 75Mi
    limits:
      cpu: 100m
      memory: 150Mi

buildtype:
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 200m
      memory: 200Mi

plugins:
  resources:
    requests:
      cpu: 50m
      memory: 150Mi
    limits:
      cpu: 100m
      memory: 300Mi

toolsMountPath: /downloads/tools
toolsSubPath: tsc/tools

vsCodeExtensionCardExtract: true

flogopluginsA:
  tp-flogo-connector-amazons3:
    tags:
      - 1.3.1-b02
    default: 1.3.1-b02
  tp-flogo-connector-aws:
    tags:
      - 1.2.2-b02
    default: 1.2.2-b02
  tp-flogo-connector-awskinesis:
    tags:
      - 1.1.1-b01-flogo-2.25.0
    default: 1.1.1-b01-flogo-2.25.0
  tp-flogo-connector-azconnection:
    tags:
      - 1.0.1-b03
    default: 1.0.1-b03
  tp-flogo-connector-azdatafactory:
    tags:
      - 1.1.1-b03
    default: 1.1.1-b03
  tp-flogo-connector-azservicebus:
    tags:
      - 1.4.3-b02
    default: 1.4.3-b02
  tp-flogo-connector-azstorage:
    tags:
      - 1.2.0-b04
    default: 1.2.0-b04

flogopluginsB:
  tp-flogo-connector-docusign:
    tags:
      - 3.0.1-hf1-b01
    default: 3.0.1-hf1-b01
  tp-flogo-connector-ems:
    tags:
      - 1.0.3-b03
    default: 1.0.3-b03
  tp-flogo-connector-gcps:
    tags:
      - 1.0.1-hf1-b01
    default: 1.0.1-hf1-b01
  tp-flogo-connector-general:
    tags:
      - 1.6.11-b02
    default: 1.6.11-b02
  tp-flogo-connector-http:
    tags:
      - 1.1.1-b03
    default: 1.1.1-b03
  tp-flogo-connector-kafka:
    tags:
      - 1.3.4-b02
    default: 1.3.4-b02
  tp-flogo-connector-lambda:
    tags:
      - 1.3.2-hf1-b01
    default: 1.3.2-hf1-b01

flogopluginsC:
  tp-flogo-connector-mongodb:
    tags:
      - 1.1.1-b01
    default: 1.1.1-b01
  tp-flogo-connector-mqtt:
    tags:
      - 1.3.1-b02
    default: 1.3.1-b02
  tp-flogo-connector-mysql:
    tags:
      - 2.4.5-b03
    default: 2.4.5-b03
  tp-flogo-connector-oracledb:
    tags:
      - 1.2.3-b03
    default: 1.2.3-b03
  tp-flogo-connector-postgres:
    tags:
      - 2.7.1-b01
    default: 2.7.1-b01
  tp-flogo-connector-pulsar:
    tags:
      - 1.3.5-b01
    default: 1.3.5-b01
  tp-flogo-connector-redis:
    tags:
      - 1.3.1-b04
    default: 1.3.1-b04

flogopluginsD:
  tp-flogo-connector-salesforce:
    tags:
      - 1.3.7-b01
    default: 1.3.7-b01
  tp-flogo-connector-snowflake:
    tags:
      - 1.2.0-b05
    default: 1.2.0-b05
  tp-flogo-connector-sns:
    tags:
      - 1.0.1-b02
    default: 1.0.1-b02
  tp-flogo-connector-sqlserver:
    tags:
      - 2.6.1-b03
    default: 2.6.1-b03
  tp-flogo-connector-sqs:
    tags:
      - 1.0.2-b01
    default: 1.0.2-b01
  tp-flogo-connector-tcm:
    tags:
      - 1.4.0-b11
    default: 1.4.0-b11
  tp-flogo-connector-tdv:
    tags:
      - 1.1.2-b05
    default: 1.1.2-b05

flogopluginsE:
  tp-flogo-connector-odata:
    tags:
      - 1.0.0-b07
    default: 1.0.0-b07
  tp-flogo-connector-websocket:
    tags:
      - 1.0.1-b03-flogo-2.25.0
    default: 1.0.1-b03-flogo-2.25.0
  tp-flogo-connector-sftp:
    tags:
      - 1.0.2-b01
    default: 1.0.2-b01
  tp-flogo-connector-files:
    tags:
      - 1.0.0-b14
    default: 1.0.0-b14
  tp-flogo-connector-ibmmq:
    tags:
      - 2.2.0-b11
    default: 2.2.0-b11
  tp-flogo-connector-mailchimp:
    tags:
      - 1.0.1-b02
    default: 1.0.1-b02
  tp-flogo-connector-gsheets:
    tags:
      - 1.0.0-hf1-b03
    default: 1.0.0-hf1-b03

flogopluginsF:
  tp-flogo-connector-google:
    tags:
      - 1.0.2-hf1-b01
    default: 1.0.2-hf1-b01
  tp-flogo-connector-sap:
    tags:
      - 1.0.0-hf1-b04
    default: 1.0.0-hf1-b04
  tp-flogo-connector-saps4hana:
    tags:
      - 1.3.0-hf1-b05
    default: 1.3.0-hf1-b05
  tp-flogo-connector-auditsafe:
    tags:
      - 1.0.1-b02
    default: 1.0.1-b02
  tp-flogo-connector-sapsolutions:
    tags:
      - 1.0.0-hf1-b01
    default: 1.0.0-hf1-b01
  tp-flogo-connector-mcp:
    tags:
      - 0.9.1-b11
    default: 0.9.1-b11
  tp-flogo-connector-databricks:
    tags:
      - 1.0.0-b04
    default: 1.0.0-b04

volumes:
  plugins:
    volumePath: "/data/"
    mountPath: /usr/share/nginx/html
    toolsMountPath: /downloads/tools
    subPath: integration

flogopluginsExtractA: true
flogopluginsExtractB: true
flogopluginsExtractC: true
flogopluginsExtractD: true
flogopluginsExtractE: true
flogopluginsExtractF: true
buildtypesExtract: true

cleanupJob: false

flogoBuildtypeImages:
  - name: tp-flogo-buildtype
    extract_image: true
    path: /var/lib/flogo/buildtypes/
    tag: 2.25.11-b341
    target_location: flogo/buildtypes

probes:
  startupProbe: {}
