# Copyright Â© 2024. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
apiVersion: v2
name: dp-configure-namespace
description: A Helm chart for creating service account, cluster-role, cluster-role-binding, role-binding & network-policies
type: application
version: 1.2.28
appVersion: "1.2.0"
