# Copyright Â© 2025. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
apiVersion: v2
name: dp-configure-namespace
description: A Helm chart for creating service account, cluster-role, cluster-role-binding, role-binding & network-policies
type: application
version: 1.15.4
appVersion: "1.15.0"
dependencies:
- condition: config.enabled
  name: config
  repository: ""
  version: 1.9.*
- condition: haproxy.enabled
  name: haproxy
  repository: ""
  version: 1.46.2
