#
# Copyright Â© 2023 - 2024. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#
{{ if eq .Values.mode "deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "otel-collector.consts.deploymentName" . }}
  namespace: {{ template "otel-collector.namespace" . }}
  labels:
    {{- include "otel-collector.labels" . | nindent 4 }}
  {{- if .Values.annotations }}
  annotations:
    {{- range $key, $value := .Values.annotations }}
    {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount | default 1 }}
{{- end }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "otel-collector.selectorLabels" . | nindent 6 }}
      {{- include "otel-collector.component" . | nindent 6 }}
  strategy:
    {{- if eq .Values.rollout.strategy "RollingUpdate" }}
    {{- with .Values.rollout.rollingUpdate }}
    rollingUpdate:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- end }}
    type: {{ .Values.rollout.strategy }}
  template:
    metadata:
      annotations:
        {{- include "otel-collector.configTemplateChecksumAnnotation" . | nindent 8 }}
        {{- include "otel-collector.podAnnotations" . | nindent 8 }}
      labels:
        networking.platform.tibco.com/internet-egress: enable
        networking.platform.tibco.com/logServer-egress: enable
        {{- include "otel-collector.selectorLabels" . | nindent 8 }}
        {{- include "otel-collector.component" . | nindent 8 }}
        {{- include "otel-collector.podLabels" . | nindent 8 }}
    spec:
      {{- with .Values.dnsPolicy }}
      dnsPolicy: {{ . }}
      {{- end }}
      {{- with .Values.dnsConfig }}
      dnsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- $podValues := deepCopy .Values }}
      {{- $podData := dict "Values" $podValues "configmapSuffix" "" "isAgent" false }}
      {{- include "otel-collector.pod" ($podData | mustMergeOverwrite (deepCopy .)) | nindent 6 }}
      hostNetwork: {{ .Values.hostNetwork }}
{{- end }}
