#
# Copyright Â© 2023 - 2025. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#

apiVersion: v2
name: opentelemetry-collector
version: 0.140.3
description: OpenTelemetry Collector Helm chart for Kubernetes
appVersion: 0.140.0
