# Copyright Â© 2025. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#
apiVersion: v2
name: tp-cp-integration-flogo
version: 1.12.12
appVersion: 1.12.0
description: TIBCO Platform Control Plane -- Integration for Flogo
dependencies:
  - name: flogo-webserver
    version: "1.12.*"
    condition: flogo-webserver.enabled
