#
# Copyright Â© 2023 - 2025. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#


apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tp-cp-configuration.name" . }}-integrationcore
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tp-cp-configuration.labels" . | nindent 4 }}
data:
  version.json: |
    {
      "capabilityVersion": "1.13.0",
      "minCPVersion": "1.1.0",
      "maxCPVersion": "",
      "releaseDate": {{ .Values.capabilities.integrationcore.releaseDate | quote }},
      "releaseNotes": {{ .Values.capabilities.integrationcore.releaseNotes | quote }},
      "minVersionRequiredForUpgrade": "1.0.0",
      "minDPVersion": {
        "dp-core-infrastructure": "1.4.0",
        "dp-configure-namespace": "1.4.0"
      }
    }
  package.json: |
    {
      "package": {
        "services": [
          {
            "name": "artifactmanager",
            "description": "Artifact Manager",
            "monitoringPriority": "essential"
          }
        ],
        "dependsOn": [],
        "provisioningRoles": [
          "DEV_OPS"
        ],
        "allowMultipleInstances": false,
        "capabilityResourceDependencies": [
          {
            "resourceType": "INFRA",
            "required": true,
            "resourceId": "STORAGE",
            "type": "Storage Class"
          }
        ]
      }
    }
  recipe.yaml: |
    recipe:
      helmCharts:
        - name: artifactmanager
          namespace: ${NAMESPACE}
          version: {{ .Values.capabilities.integrationcore.artifactmanager.version | quote }}
          repository:
            chartMuseum:
              host: ${HELM_REPO}
          values:
            - content: |
                global:
                  artifactmanager:
                    image:
                      tag: {{ .Values.capabilities.integrationcore.artifactmanager.tag | quote }}
                volumes:
                  artifactmanager:
                    persistentVolumeClaim:
                      resources:
                        requests:
                          storage: 20Gi
          flags:
            install: true
            createNamespace: false
            dependencyUpdate: true

---

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "tp-cp-configuration.name" . }}-integrationcore-{{ randAlphaNum 4 | lower }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tp-cp-configuration.labels" . | nindent 4 }}
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 3600
  template:
    metadata:
      labels:
        {{- include "tp-cp-configuration.labels" . | nindent 8 }}
    spec:
    {{- if .Values.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
    {{- end }}
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: integrationcore
        image: {{ include "tp-cp-configuration.image.registry" .}}{{"/"}}{{ include "tp-cp-configuration.image.repository" .}}{{"/"}}{{ .Values.image.name }}:{{ .Values.image.tag}}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- if .Values.securityContext }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        {{- end }}
        {{- if eq (include "tp-cp-configuration.enableResourceConstraints" . ) "true" }}
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10}}
        {{- end }}
        {{- end }}
        env:
        - name: CAPABILITY_NAME
          value: "integrationcore"
        - name: RECIPE_MOUNT_LOCATION
          value: "/opt/tibco/recipe"
        - name: RECIPE_TARGET_LOCATION
          value: "/private/tsc/config/capabilities/infra"
        - name: RECIPE_RELEASE_VERSION
          value: "1.13.0"
        - name: SPACE_SEPARATED_UNSUPPORTED_RECIPE_VERSIONS
          value: ""
        - name: OVERWRITE_RECIPE
          value: {{ .Values.capabilities.integrationcore.overwriteRecipe | quote }}
        - name: IS_LATEST
          value: {{ .Values.capabilities.integrationcore.isLatest | quote }}
        volumeMounts:
        - name: {{ include "tp-cp-configuration.name" . }}-integrationcore-volume
          mountPath: /opt/tibco/recipe
        - name: scripts-config-volume
          mountPath: /opt/tibco/scripts
        - name: store-vol
          mountPath: /private/tsc/config
          subPath: tsc/config
        command: ["sh"]
        args: ["-c", "/opt/tibco/scripts/run.sh"]
      restartPolicy: Never
      volumes:
        - name: {{ include "tp-cp-configuration.name" . }}-integrationcore-volume
          configMap:
            name: {{ include "tp-cp-configuration.name" . }}-integrationcore
        - name: scripts-config-volume
          configMap:
            name: {{ include "tp-cp-configuration.name" . }}-script
            defaultMode: 0777
        - name: store-vol
          persistentVolumeClaim:
            claimName: {{ include "tp-cp-configuration.pvc-name" . }}
      imagePullSecrets:
        {{- if (include "tp-cp-configuration.container-registry.secret" .) }}
        - name: {{ include "tp-cp-configuration.container-registry.secret" . }}
        {{- end}}