#
# Copyright Â© 2023 - 2024. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#

kind: TibcoRoute
apiVersion: cloud.tibco.com/v1
metadata:
  name: {{ include "tp-cp-configuration.compute-services.consts.appName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "tp-cp-configuration.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "tp-cp-configuration.compute-services.consts.appName" . }}
  endpoints:
    - path: /infra/versions
      protocol: http
      port: 80
      internalPath: /infra/versions
      proxies:
        - listener: virtual
          config: insecure
          fqdn:  {{ .Values.global.tibco.adminHostPrefix | default "admin" }}.{{ include "tp-cp-configuration.dns-domain" . }}
