# Copyright Â© 2026. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.

{{- range $crd := .Values.crds }}
---
{{- toYaml . }}
{{- end }}
