# Copyright Â© 2026. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.

{{ if .Values.ingress.enabled -}}
{{- if eq .Values.ingress.controllerName "haProxy" -}}
{{- $dot := . }}
{{- range $rule := .Values.ingress.rules -}}
{{- range $path := $rule.paths }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    platform.tibco.com/controller-name: {{ $.Values.ingress.controllerName | quote }}
    platform.tibco.com/resource-instance-name: {{ $.Values.ingress.resourceInstanceName | quote }}
    haproxy.org/request-set-header: |
      X-Forwarded-Host %[req.hdr(host)]
      X-Forwarded-Port 443
      X-Forwarded-Proto https
      X-Forwarded-Prefix {{ $path.path }}
    {{- if eq $path.path "/" }}
    ingress.kubernetes.io/path-rewrite: {{ $path.path }}(.*) /\1
    {{- else }}
    ingress.kubernetes.io/path-rewrite: {{ $path.path }}(/|$)(.*) /\2
    {{- end }}
    {{- if $path.serviceDiscoverable }}
    platform.tibco.com/service-description: {{ $path.serviceDescription | squote }}
    {{- end }}
    {{- with $.Values.ingress.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "dp-flogo-app.labels" $dot | nindent 4 }}
    platform.tibco.com/service-discoverable: {{ $path.serviceDiscoverable | quote }}
  name: {{ include "dp-flogo-app.fullname" $dot }}-{{ $path.port }}
spec:
  ingressClassName: {{ $.Values.ingress.className }}
  {{- if $.Values.ingress.tls }}
  tls:
    {{- range $.Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
  - host: {{ $rule.host | quote }}
    http:
      paths:
      - backend:
          service:
            name: {{ include "dp-flogo-app.fullname" $dot }}
            port:
              number: {{ $path.port }}
        {{- if eq $path.path "/" }}
        path: {{ $path.path }}
        {{- else }}
        path: {{ $path.path }}/
        {{- end }}
        pathType: {{ $path.pathType }}
        
{{- end }}
{{- end }}
{{- end }}
{{- end }}
