# Copyright Â© 2025. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bw-recipes.appName" . }}-bwce
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bw-recipes.labels" . | nindent 4 }}
data:
  version.json: |
    {
      "capabilityVersion": "1.14.0",
      "minCPVersion": "1.14.0",
      "maxCPVersion": "",
      "releaseDate": {{ .Values.capabilities.bwce.releaseDate | quote }},
      "releaseNotes": {{ .Values.capabilities.bwce.releaseNotes | quote }},
      "minVersionRequiredForUpgrade": "1.4.0",
      "minDPVersion": {
        "dp-core-infrastructure": "1.12.0",
        "dp-configure-namespace": "1.8.0"
      }
    }
  package.json: |
    {
      "package": {
        "services": [
          {
            "name": "bwprovisioner",
            "description": "BW Provisioner Service",
            "monitoringPriority": "essential"
          },
          {
            "name": "dp-bwce-mon",
            "description": "BWCE Monitoring Service",
            "monitoringPriority": "optional"
          }
        ],
        "dependsOn": [
          {
            "version": [
              1,
              11,
              0
            ],
            "capabilityId": "INTEGRATIONCORE",
            "capabilityType": "INFRA"
          }
        ],
        "provisioningRoles": [
          "DEV_OPS"
        ],
        "serviceUrl": "http://bwprovisioner:7816",
        "allowMultipleInstances": false,
        "capabilityResourceDependencies": [
          {
            "type": "Ingress Controller",
            "required": true,
            "resourceId": "INGRESS",
            "resourceType": "PLATFORM"
          },
          {
            "type": "Database Resource",
            "required": false,
            "resourceId": "DBCONFIG",
            "resourceType": "PLATFORM"
          }
        ]
      }
    }
  recipe.yaml: |
    recipe:
      helmCharts:
        - name: bwprovisioner
          namespace: ${NAMESPACE}
          version: "1.14.2"
          repository:
            chartMuseum:
              host: ${HELM_REPO}
          values:
            - content: |
                global:
                  cp:
                    logging:
                      fluentbit:
                        apps:
                          enabled: ${ENABLE_APPS_FLUENTBIT_SIDECAR}
                  bwprovisioner:
                    image:
                      tag: 849
                config:
                  APP_INIT_IMAGE_TAG: "60"
                  BWCE_APP_HELMCHART_VERSION: "1.14.4"
                  ENABLE_NON_TOKENIZED_PROPS: ${ENABLE_NON_TOKENIZED_PROPS}
                  INFRA_CP_PROXY_IMAGE_TAG: "291"
                autoDiscovery:
                  enabled: ${ENABLE_APP_DISCOVERY}
                  config:
                    APP_DISCOVERY_LABEL_SELECTOR: ${APP_DISCOVERY_LABEL_SELECTOR}
                    APP_DISCOVERY_ENGINE_PORT: ${APP_DISCOVERY_ENGINE_PORT}
                publicApi:
                  ingress:
                    controllerName: ${INGRESS_CONTROLLER_NAME}
                    config:
                      className: ${INGRESS_CLASS_NAME}
                      pathPrefix: ${INGRESS_PATH_PREFIX}
                      fqdn: ${INGRESS_FQDN}
          flags:
            install: true
            createNamespace: false
            dependencyUpdate: true
        - name: dp-bwce-mon
          namespace: ${NAMESPACE}
          version: "1.14.1"
          repository:
            chartMuseum:
              host: ${HELM_REPO}
          values:
            - content: |
                enabled: ${ENABLE_EXEC_HISTORY}
                global:
                  bwcemon:
                    image:
                      tag: 6.12.0-HF1
          flags:
            install: true
            createNamespace: false
            dependencyUpdate: true

---

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "bw-recipes.appName" . }}-bwce-{{ randAlphaNum 4 | lower }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bw-recipes.labels" . | nindent 4 }}
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 3600
  template:
    metadata:
      labels:
        {{- include "bw-recipes.labels" . | nindent 8 }}
    spec:
    {{- if .Values.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
    {{- end }}
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: bwce
        image: {{ include "bw-recipes.image.registry" .}}{{"/"}}{{ include "bw-recipes.image.repository" .}}{{"/"}}{{ .Values.image.name }}:{{ .Values.image.tag}}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- with .Values.probes.startupProbe }}
        startupProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- if .Values.securityContext }}
        securityContext:
        {{- toYaml .Values.securityContext | nindent 10 }}
        {{- end }}
        {{- if $.Values.global.tibco.enableResourceConstraints }}
        resources:
        {{- toYaml .Values.scripts.resources | nindent 10 }}
        {{- end }}
        env:
        - name: CAPABILITY_NAME
          value: "bwce"
        - name: RECIPE_MOUNT_LOCATION
          value: "/opt/tibco/recipe"
        - name: RECIPE_TARGET_LOCATION
          value: "/private/tsc/config/capabilities/platform"
        - name: RECIPE_RELEASE_VERSION
          value: "1.14.0"
        - name: SPACE_SEPARATED_UNSUPPORTED_RECIPE_VERSIONS
          value: ""
        - name: OVERWRITE_RECIPE
          value: {{ .Values.capabilities.bwce.overwriteRecipe | quote }}
        - name: IS_LATEST
          value: {{ .Values.capabilities.bwce.isLatest | quote }}          
        volumeMounts:
        - name: {{ include "bw-recipes.appName" .  }}-bwce-volume
          mountPath: /opt/tibco/recipe
        - name: scripts-config-volume
          mountPath: /opt/tibco/scripts
        - name: store-vol
          mountPath: /private/tsc/config
          subPath: tsc/config
        - name: tmp-vol
          mountPath: /tmp
        command: ["sh"]
        args: ["-c", "/opt/tibco/scripts/run.sh"]
      restartPolicy: Never
      volumes:
        - name: {{ include "bw-recipes.appName" . }}-bwce-volume
          configMap:
            name: {{ include "bw-recipes.appName" . }}-bwce
        - name: scripts-config-volume
          configMap:
            name: {{ include "bw-recipes.appName" . }}-script
            defaultMode: 0777
        - name: store-vol
          persistentVolumeClaim:
            claimName: {{ include "bw-recipes.pvc-name" . }}
        - emptyDir: {}
          name: tmp-vol
{{- if (include "bw-recipes.container-registry.secret" .) }}
      imagePullSecrets:
        - name: {{ include "bw-recipes.container-registry.secret" . }}
{{- end }}
