#
# Copyright Â© 2024. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#

finops:
  ## This is used to delete the DB while Uninstalling the Chart. Default it is set to false so it will just take the backup of DB, data in DB will be retained as it is.
  ## If it is set to true then, it will take the DB backup and wipe-out the DB (i.e. It will clean the schema, database, users. )
  deleteDBOnUninstall: "false"
# Global section will apply to this chart and all of its subcharts.
global:
  tibco:
    # Flag to enable or disable database jobs (upgrade and cleanup)
    # Set to false to disable DB script execution if you want to run scripts manually outside of the chart
    # Default value is true
    manageDbSchema: true
    db_ssl_root_cert_secretname: "db-ssl-root-cert"
    db_ssl_root_cert_filename: "db_ssl_root.cert"
    is_replica_region: false
    containerRegistryImagePullSecretName: ""
    containerRegistry:
      url: ""
      username: ""
      password: ""
      repository: "tibco-platform-docker-prod"  # repository
    controlPlaneInstanceId: ""
    logging:
      fluentbit:
        enabled: true
  # Pod Security Context configuration
  # This configuration ensures that the pod is run with non-root privileges for enhanced security.
  # The user, group, and filesystem group IDs are all set to 1000.
  # The filesystem group change policy is set to "Always", meaning the filesystem group is always set to the fsGroup.
  # The seccomp (secure computing mode) profile is set to RuntimeDefault, which means it uses the default profile provided by the runtime.
  # The sysctls configuration allows the platform hybrid proxy to bind to low ports (below 1024) as a non-root user.
  # This is achieved by setting the 'net.ipv4.ip_unprivileged_port_start' sysctl to 0.
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    fsGroupChangePolicy: "Always"
    seccompProfile:
      type: RuntimeDefault
  containerSecurityContext:
    # It specifies that privilege escalation is not allowed for security reasons.
    # Additionally, it drops all capabilities, which is a common security practice to minimize potential risks.
    finopsJob:
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
          - CAP_NET_RAW
  cp:
    containerRegistry:
      url: "csgprdusw2reposaas.jfrog.io"
      secret: "test"
  CP_HELM_REPO: "https://raw.githubusercontent.com/tibco/tp-helm-charts/gh-pages"
  CP_PROD_HELM_REPO: "https://tibcosoftware.github.io/tp-helm-charts"
  CP_STAGING_HELM_REPO: "https://tibcosoftware.github.io/tp-helm-charts"
  # Github repo path to read contribution ui code
  GITHUB_CONTRIBUTORS_REPO: "https://raw.githubusercontent.com/tibco/tp-cp-web-contributors/master/releases"
  # Valid values for UI_CONTRIBUTORS_SOURCE are "EFS" and "GitHub"
  UI_CONTRIBUTORS_SOURCE: "GitHub"
  external:
    cpEncryptionSecretName: "cporch-encryption-secret"
    cpEncryptionSecretKey: "CP_ENCRYPTION_SECRET"
    environment: "production"
    db_secret_name: ""
    storage:
      pvcName: control-plane-pvc
      providerName: aws

capabilities:
  monitorAgent:
    # if set to true then existing recipe will be overwritten by latest recipe.
    overwriteRecipe: "false"
    # set to true for latest version of recipe
    isLatest: "true"
    # Helm chart version for monitor-agent, default is latest
    version: "1.15.228"
    tag: "380"
    # Timestamp of capability release
    releaseDate: "2024/07/22"
    # Either a link to document or the document itself specifying _what was fixed in this release.
    releaseNotes: "Enhancements, Bug fixes, etc."
podRecipeSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  fsGroupChangePolicy: "Always"
  seccompProfile:
    type: RuntimeDefault

image:
  name: common-distroless-base-debian-debug
  tag: 12.13
  pullPolicy: IfNotPresent

securityContext:
  # It specifies that privilege escalation is not allowed for security reasons.
  # Additionally, it drops all capabilities, which is a common security practice to minimize potential risks.
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL

resources:
  requests:
    cpu: 50m
    memory: 30Mi
  limits:
    cpu: 100m
    memory: 60Mi
