{{- if eq .Values.global.tibco.is_replica_region false }}
{{- if .Values.global.tibco.manageDbSchema }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "tp-control-plane.consts.appName" . }}-upgrade-{{ randAlphaNum 4 | lower }}
  namespace: {{ include "tp-control-plane.consts.namespace" . }}
  labels:
    {{- include "tp-control-plane.shared.labels.standard" . | nindent 4 }}
spec:
  backoffLimit: 0
  template:
    metadata:
      name: {{ include "tp-control-plane.consts.appName" . }}-upgrade
      labels:
        {{- include "tp-control-plane.shared.labels.standard" . | nindent 8 }}
        networking.platform.tibco.com/kubernetes-api: enable
        networking.platform.tibco.com/cluster-egress: enable
        networking.platform.tibco.com/internet-egress: enable
        networking.platform.tibco.com/database-egress: enable
    spec:
      {{- if .Values.global.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.global.podSecurityContext | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cp-core-configuration.service-account-name" . }}
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Never
      {{- if (include "cp-core-configuration.container-registry.secret" .) }}
      imagePullSecrets:
        - name: {{ include "cp-core-configuration.container-registry.secret" . }}
      {{- end }}
      containers:
      - name: tsc-upgrade
        {{- if .Values.global.containerSecurityContextTpcpcoreJob }}
        securityContext:
          {{- toYaml .Values.global.containerSecurityContextTpcpcoreJob | nindent 10 }}
        {{- end }}
        image: {{ include "cp-core-configuration.container-registry" .}}{{"/"}}{{ include "cp-core-configuration.image-repository" . }}{{"/"}}{{ .Values.global.tibco.image_name.cpScripts }}:{{ include "cp-core-scripts.buildNumber" . }}
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_PREFIX
          value: {{ .Values.global.tibco.controlPlaneInstanceId }}_
        - name: PGHOST
          valueFrom:
            configMapKeyRef:
              name: {{ include "tp-cp-core.consts.cp.db.configuration" . }}
              key: DBHost
        - name: PGPORT
          valueFrom:
            configMapKeyRef:
              name: {{ include "tp-cp-core.consts.cp.db.configuration" . }}
              key: DBPort
        - name: MASTER_PGUSER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.global.external.db_secret_name }}
              key: USERNAME
        - name: MASTER_PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.global.external.db_secret_name }}
              key: PASSWORD
        - name: MASTER_PGDATABASE
          valueFrom:
            configMapKeyRef:
              name: {{ include "tp-cp-core.consts.cp.db.configuration" . }}
              key: DBName
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: AWS_REGION
          value: {{ .Values.global.tibco.region }}
        - name: ENVIRONMENT_TYPE
          value: {{ (.Values.global.external.environment | lower) }}
        - name: PSQL_SCRIPTS_LOCATION
          value: /opt/tibco/tsc/scripts/postgres/tibco-cp-base
        - name: BASE_SCRIPTS_LOCATION
          value: /opt/tibco/base/scripts
        - name: TSC_CONFIG_LOCATION
          value: /opt/tibco/tsc/config
        - name: TSC_CERTIFICATES_LOCATION
          value: /opt/tibco/tsc/certificates
        - name: TSC_VOLUME_LOCATION
          value: /tmp/private/tsc
        - name: DB_SSL_MODE
          value: {{ .Values.global.external.db_ssl_mode }}
        - name: DB_SSL_CERT_SECRET_NAME
          value: {{ .Values.global.tibco.db_ssl_root_cert_secretname }}
        command:
          - "/bin/bash"
          - "-c"
          - |
            # Check the DB_SSL_MODE
            if [ $DB_SSL_MODE == "disable"  ]; then
              echo "No certificate check required. Proceeding"
            else
              # Check if the Kubernetes secret exists (using kubectl)
              if [ -z $DB_SSL_CERT_SECRET_NAME ]; then
                echo "ERROR: The value for global.tibco.db_ssl_root_cert_secretname cannot be empty when ssl mode is set to $DB_SSL_MODE. Exiting"
                exit 1
              else
                #If the SSL_MODE is not disable then check the presence of the DB SSL secret in the namespace
                if kubectl get secret $DB_SSL_CERT_SECRET_NAME >/dev/null 2>&1; then
                    echo "Kubernetes secret $DB_SSL_CERT_SECRET_NAME found. Proceeding..."
                  else
                    echo "ERROR: Certificate secret $DB_SSL_CERT_SECRET_NAME not found. Exiting."
                    exit 2
                fi
              fi
            fi
            /opt/tibco/tsc/scripts/postgres-helper.bash upgrade
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
      volumes:
        - name: tmp-volume
          emptyDir: {}

{{- end }}
{{- end }}

---

{{- if eq .Values.global.tibco.self_hosted_deployment true }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "tp-control-plane.consts.appName" . }}-security-certs-{{ randAlphaNum 4 | lower }}
  annotations:
    description: "Job to create self-signed certs and secrets for IdM and IdP services in self-hosted deployment."
    "helm.sh/depends-on": "ConfigMap/cp-core-scripts-config"
  namespace: {{ include "tp-control-plane.consts.namespace" . }}
  labels:
    {{- include "tp-control-plane.shared.labels.standard" . | nindent 4 }}
spec:
  backoffLimit: 0
  activeDeadlineSeconds: 180 # Timeout and terminate after 60 seconds
  ttlSecondsAfterFinished: 3600 # Remove the job 1 hour after completion
  template:
    metadata:
      name: {{ include "tp-control-plane.consts.appName" . }}-security-certs
      labels:
        {{- include "tp-control-plane.shared.labels.standard" . | nindent 8 }}
        networking.platform.tibco.com/kubernetes-api: enable
    spec:
      {{- if .Values.global.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.global.podSecurityContext | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cp-core-configuration.service-account-name" . }}
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Never
      {{- if (include "cp-core-configuration.container-registry.secret" .) }}
      imagePullSecrets:
        - name: {{ include "cp-core-configuration.container-registry.secret" . }}
      {{- end }}
      containers:
      - name: tsc-setup
        {{- if .Values.global.containerSecurityContextTpcpcoreJob }}
        securityContext:
          {{- toYaml .Values.global.containerSecurityContextTpcpcoreJob | nindent 10 }}
        {{- end }}
        image: {{ include "cp-core-configuration.container-registry" .}}{{"/"}}{{ include "cp-core-configuration.image-repository" . }}{{"/"}}{{ .Values.global.tibco.image_name.cpScripts }}:{{ include "cp-core-scripts.buildNumber" . }}
        imagePullPolicy: IfNotPresent
        workingDir: /tmp # Use tmp folder which is mounted to this container and is writable
        env:
        - name: TSC_CONFIG_LOCATION
          value: /private/tsc/config
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        command: [ "/bin/bash", "-c" ]
        args:
        - |
          /scripts/certs/generate-self-signed-cert.sh idm && /scripts/certs/generate-self-signed-cert.sh idp
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: scripts-certs
          mountPath: /scripts/certs
        - name: store-vol
          mountPath: /private/tsc
          subPath: tsc
      volumes:
        - name: tmp
          emptyDir: {} # emptyDir volume for generating certificates, is by default writable
        - name: store-vol
          persistentVolumeClaim:
            claimName: {{ include "cp-core-configuration.pvc-name" . }}
        - name: scripts-certs
          configMap:
            name: cp-core-scripts-config
            items:
              - key: files__tsc__scripts__certs__generate-self-signed-cert.sh
                path: generate-self-signed-cert.sh
            defaultMode: 0755
{{- end }}
