# Copyright Â© 2026. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.

apiVersion: v2
name: dp-bw5ce-app
description: A Helm chart for BW5 Containers application
type: application
version: 1.15.6
appVersion: "1.15.0"
