#    Copyright 2025 Alert Manager Community Charts

#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at

#    http://www.apache.org/licenses/LICENSE-2.0

#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.


apiVersion: v2
name: tp-cp-alertmanager
description: The Alertmanager handles alerts sent by client applications such as the Prometheus server.
type: application
version: 1.15.0
appVersion: 1.15.0
kubeVersion: ">=1.19.0-0"
keywords:
  - monitoring
