#
# Copyright (c) 2023-2025. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#

apiVersion: v2
appVersion: 10.4.0-85
description: Data-plane provisioning chart for EMS server group
keywords:
- tibco-platform
- data-plane
- messaging
- EMS
maintainers:
- email: tcm@tibco.com
  name: TIBCO Cloud Messaging Team
name: msg-ems-tp
version: "1.10.7"
