#
# Copyright (c) 2023-2026. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#

# Keep until o11y updates for demo installs
keepPromServices: true

# DO NOT SET .global.cp VALUES, these keys are controlled by the Control Plane
# and will be overridden by the Control Plane.
global:
  cp:
    containerRegistry:
    serviceaccount:
    dataplaneId:
    instanceId:
    enableClusterScopedPerm: true
    enableResourceConstraints: true
    logging:
      fluentbit:
        enabled: true
    resources:
      activationServer:
        url: ""

dp: {}
  # CAUTION:  Values set here will override .global.cp.*
  # See _dp.helpers.tpl to set defaults
  #
cp:
  jwks:
  adminUser: no-cp-admin

ems:
  stores: ftl
  sizing: small
  use: dev
  # CAUTION: Current chart does not support overriding internal ports
  ports:
    httpPort: 9010
    tcpPort: 9011
    sslPort: 9012
    realmPort: 9013
    adminPort: 9014
    watchdogPort: 12502
    loggerPort: 12506
  msgData:
    storageType: emptyDir
    storageName: none
  logs:
    storageType: useMsgData
    storageName: none
  sslEnable: true
  tcpEnable: true
  opsEnable: false
  ftl_spin: disabled
