#
# Copyright Â© 2023 - 2025. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#


apiVersion: v2
version: "1.13.6"
name: tp-cp-auditsafe
appVersion: "1.13.0"
description: Platform AuditSafe chart
keywords:
  - "auditsafe"
