# Copyright Â© 2025. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.

global:
  tibco:
    containerRegistry:
      url: ""
      username: ""
      password: ""
      repository: ""
      imagePullSecretName: ""
      customCertSecret: ""
    enableResourceConstraints: true
    serviceAccount: ""
    proxy:
      http: ""
      https: ""
      noproxy: ""
  external:
    storage:
      pvcName: "control-plane-pvc"

image:
  name: infra-container-image-extractor
  registry: ""
  repo: ""
  tag: 170-distroless
  pullPolicy: IfNotPresent

podAnnotations: {}

capability:
  name: tibco-hub

source:
  directory: /app

tibcoHub:
  image:
    name: "dx-tibco-hub-cp-contrib"
    tag: "301"
    pullPolicy: IfNotPresent

target:
  directory: /efs/tibcohub

# Pod Security Context configuration
# This configuration ensures that the pod is run with non-root privileges for enhanced security.
# The user, group, and filesystem group IDs are all set to 1000.
# The filesystem group change policy is set to "Always", meaning the filesystem group is always set to the fsGroup.
# The seccomp (secure computing mode) profile is set to RuntimeDefault, which means it uses the default profile provided by the runtime.
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  fsGroupChangePolicy: "Always"
  seccompProfile:
    type: RuntimeDefault

securityContext:
  # It specifies that privilege escalation is not allowed for security reasons.
  # Additionally, it drops all capabilities, which is a common security practice to minimize potential risks.
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL
      - CAP_NET_RAW


scripts:
  resources:
    requests:
      cpu: 50m
      memory: 75Mi
    limits:
      cpu: 100m
      memory: 150Mi

probes:
  startupProbe: {}
  # enable startup probe only if security policy is blocking you from deployment, otherwise its not recommended to use it
  #  exec:
  #    command:
  #    - touch
  #    - /tmp/healthy
  #  initialDelaySeconds: 5
  #  periodSeconds: 5
  #  failureThreshold: 5
  #  successThreshold: 1
  #  timeoutSeconds: 5
