#
# Copyright Â© 2023 - 2025. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#


apiVersion: v1
appVersion: "1.15.0"
description: A Helm chart for TIBCO Tibtunnel
keywords:
- tibtunnel
- data-plane
- hybrid-connectivity
name: tp-tibtunnel
version: 1.15.0

