# Copyright Â© 2025. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.

capabilities:
  bwce:
    # if set to true then existing recipe will be overwritten by latest recipe.
    overwriteRecipe: "true"
    # set to true for latest version of recipe
    isLatest: "true"
    # Timestamp of capability release
    releaseDate: "2025/03/28"
    # Either a link to document or the document itself specifying _what was fixed in this release.
    releaseNotes: "#cshid=new_features"
    # helm chart and image version for bwprovisioner, default helm chart version is latest
    bwprovisioner:
      version: ""
      tag: "46"
  bwadapter:
    # if set to true then existing recipe will be overwritten by latest recipe.
    overwriteRecipe: "true"
    # set to true for latest version of recipe
    isLatest: "true"
    # Timestamp of capability release
    releaseDate: "2025/02/28"
    # Either a link to document or the document itself specifying _what was fixed in this release.
    releaseNotes: "#cshid=new_features"
    # helm chart and image version for bwprovisioner, default helm chart version is latest
    bwadapter:
      version: ""
      tag: "7"

image:
  name: common-distroless-base-debian-debug
  registry: ""
  repo: ""
  tag: 12
  pullPolicy: IfNotPresent

# Pod Security Context configuration
# This configuration ensures that the pod is run with non-root privileges for enhanced security.
# The user, group, and filesystem group IDs are all set to 1000.
# The filesystem group change policy is set to "Always", meaning the filesystem group is always set to the fsGroup.
# The seccomp (secure computing mode) profile is set to RuntimeDefault, which means it uses the default profile provided by the runtime.
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  fsGroupChangePolicy: "Always"
  seccompProfile:
    type: RuntimeDefault

securityContext:
  # It specifies that privilege escalation is not allowed for security reasons.
  # Additionally, it drops all capabilities, which is a common security practice to minimize potential risks.
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL
      - CAP_NET_RAW

scripts:
  resources:
    requests:
      cpu: 150m
      memory: 150Mi
    limits:
      cpu: 300m
      memory: 300Mi

probes:
  startupProbe: {}
  # enable startup probe only if security policy is blocking you from deployment, otherwise its not recommended to use it
  #  exec:
  #    command:
  #    - touch
  #    - /tmp/healthy
  #  initialDelaySeconds: 5
  #  periodSeconds: 5
  #  failureThreshold: 5
  #  successThreshold: 1
  #  timeoutSeconds: 5
