# Copyright Â© 2025. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#
apiVersion: v2
name: tibco-cp-devhub
version: 1.14.0
appVersion: 1.14.0
description: TIBCO Platform base for Developer Hub Capability
dependencies:
  - name: tibcohub-recipes
    version: "1.14.*"
    condition: tibcohub-recipes.enabled
  - name: tibcohub-contrib
    version: "1.14.*"
    condition: tibcohub-contrib.enabled
