# Copyright Â© 2026. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.

{{ if eq .Values.global.cp.resources.ingress.ingressController "haProxy" -}}
{{- $fullName := include "flogoprovisioner.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    haproxy.org/request-set-header: |
      X-Forwarded-Host %[req.hdr(host)]
      X-Forwarded-Port 443
      X-Forwarded-Proto https
      X-Forwarded-Prefix {{ .Values.publicApi.config.pathPrefix }}
    ingress.kubernetes.io/path-rewrite: {{ .Values.publicApi.config.pathPrefix }}/(.*) /\1
    {{- with .Values.global.cp.resources.ingress.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ $fullName }}-public-haproxy
spec:
  ingressClassName: {{ .Values.global.cp.resources.ingress.ingressClassName }}
  rules:
  - host: {{ .Values.global.cp.resources.ingress.fqdn }}
    http:
      paths:
      - backend:
          service:
            name: {{ $fullName }}
            port:
              number: {{ $.Values.publicApiService.targetPort }}
        path: {{ .Values.publicApi.config.pathPrefix }}/
        pathType: Prefix
{{- end }}
