# Copyright Â© 2024. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.

apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    {{- include "flogoprovisioner.labels" . | nindent 4 }}
  name: {{ include "flogoprovisioner.fullname" . }}-serviceconfig
data:
  {{- range $filename, $content :=  .Values.config }}
  {{- if $content }}
  {{ $filename }}: {{ tpl $content $ | quote }}
  {{- end }}
  {{- end }}
