#
# Copyright Â© 2023 - 2025. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#


apiVersion: v1
appVersion: 1.8.0
description: A Helm chart for TIBCO Dp Core infrastructure-- Config
home: https://github.com/tibco/cicinfra-cic2-core
icon: https://pbs.twimg.com/profile_images/1064638558110007296/K6HqaXwh_400x400.jpg
keywords:
- config
- data-plane
maintainers:
- email: compute-dev@tibco.com
  name: TIBCO CIC Compute Dev Team
name: config
version: 1.8.0
