#
# Copyright (c) 2023-2025. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#

apiVersion: v2
appVersion: 1.12.0-13
description: TIBCO Platform Control Plane -- Messaging
keywords:
- tibco-platform
- control-plane
- messaging
- EMS
maintainers:
- email: tcm@tibco.com
  name: TIBCO Cloud Messaging Team
name: tibco-cp-messaging
version: 1.12.9
