# Copyright Â© 2024. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#
apiVersion: v2
name: flogo-utilities
version: "1.3.17"
appVersion: "1.3.0"
description: TIBCO CIC Global Provider -- FLOGO Utilities
