#
#
# Copyright Â© 2023 - 2026. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#

{{ if .Values.opensearchIngress.httpRoute.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: {{ .Release.Name }}-opensearch-tls
  namespace: {{ .Release.Namespace }}
  {{- with .Values.opensearchIngress.httpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  targetRefs:
  - group: ""
    kind: Service
    name: {{ .Values.opensearch.clusterName }}-master
  validation:
    caCertificateRefs:
    - group: ""
      kind: ConfigMap
      name: opensearch-ca-cert
    # This must match the SAN in the OpenSearch certificate
    hostname: {{ .Values.opensearch.clusterName }}-master.{{ .Release.Namespace }}.svc
---

apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}-opensearch
  namespace: {{ .Release.Namespace }}
  {{- with .Values.opensearchIngress.httpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    - name: {{ .Values.opensearchIngress.httpRoute.gatewayName }}
      namespace: {{ .Values.opensearchIngress.httpRoute.gatewayNamespace | default .Release.Namespace }}
  hostnames:
    - {{ .Values.opensearchIngress.httpRoute.host }}.{{ .Values.domain }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ .Values.opensearch.clusterName }}-master
          port: 9200
{{- end -}}
