# Copyright Â© 2026. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.

apiVersion: v2
name: bw5provisioner
version: 1.15.6
appVersion: "1.15.0"
description: TIBCO Platform Dataplane Capabilty -- BW5 Provisioner
home: https://github.com/tibco/tp-iapp-bw5-provisioner.git
icon: https://pbs.twimg.com/profile_images/1064638558110007296/K6HqaXwh_400x400.jpg
maintainers:
  - name: TIBCO Platform Dev Team
    email: compute-dev@tibco.com
