#
# Copyright Â© 2023 - 2024. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#


apiVersion: v1
kind: Service
metadata:
  name: {{ include "tp-cp-proxy.consts.appName" . }}
  namespace: {{ .Release.Namespace}}
  labels:
    {{- include "tp-cp-proxy.shared.labels.standard" . | nindent 4 }}
spec:
  selector:
    {{- include "tp-cp-proxy.shared.labels.selector" . | nindent 4 }}
  ports:
  - name: proxy
    port: 80
    protocol: TCP
    targetPort: proxy
  sessionAffinity: None
  type: ClusterIP