#
# Copyright (c) 2025. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#

apiVersion: v2
name: tp-dp-license-file
description: Helm chart to provision a shared license Secret (one per DP namespace)
type: application
version: 1.13.0
appVersion: "1.13.0"
