#
# Copyright (c) 2025. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#

global:
  cp:
    dataplane:
      licenseFiles:
       # <license-filename>: <content - base64-encoded license file bytes>
