# Copyright Â© 2024. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tp-hawk-infra-querynode.consts.appName" . }}
  namespace: {{ include "tp-hawk-infra-querynode.consts.namespace" . }}
  labels:
    {{- include "tp-hawk-infra-querynode.shared.labels.standard" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "tp-hawk-infra-querynode.shared.labels.selector" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tp-hawk-infra-querynode.shared.labels.standard" . | nindent 8 }}
        networking.platform.tibco.com/database-egress: enable
        networking.platform.tibco.com/cluster-egress: enable
        networking.platform.tibco.com/cluster-ingress: enable
        networking.platform.tibco.com/internet-egress: enable
    spec:
      {{- if .Values.global.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.global.podSecurityContext | nindent 8 }}
      {{- end }}
      {{- if eq .Values.global.tibco.manageDbSchema false }}
      initContainers:
        - name: check-sql-schema-version
          image: {{ include "tp-hawk-infra-querynode.image.registry" . }}{{"/"}}{{ include "tp-hawk-infra-querynode.image.repository" . }}{{"/"}}{{ .Values.global.tibco.image_name.cpScripts }}:{{ include "cp-core-scripts.buildNumber" . }}
          {{- if .Values.global.containerSecurityContext.querynode }}
          securityContext:
            {{- toYaml .Values.global.containerSecurityContext.querynode | nindent 12 }}
          {{- end }}
          {{- if .Values.global.cp.enableResourceConstraints }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_PREFIX
              value: {{ .Values.global.tibco.controlPlaneInstanceId }}_
            - name: PGHOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.global.cp.data.CP_DB_CONFIGURATION }}
                  {{- if eq .Values.global.tibco.is_replica_region true }}
                  key: MasterWriterHost
                  {{- else }}
                  key: DBHost
                  {{- end }}
            - name: PGPORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.global.cp.data.CP_DB_CONFIGURATION }}
                  key: DBPort
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: rtmon-postgres-credential
                  key: PGPASSWORD
            - name: PSQL_SCRIPTS_LOCATION
              value: /opt/tibco/tsc/scripts/postgres/tibco-cp-hawk
          command:
            - "/bin/bash"
            - "-c"
            - |
              /opt/tibco/tsc/scripts/postgres-helper.bash check-schema-version rtmon
      {{- end }}
      {{- if (include "tp-hawk-infra-querynode.container-registry.secret" .) }}
      imagePullSecrets:
        - name: {{ include "tp-hawk-infra-querynode.container-registry.secret" . }}
      {{- end }}
      containers:
        - name: querynode
          {{- if .Values.global.containerSecurityContext.querynode }}
          securityContext:
            {{- toYaml .Values.global.containerSecurityContext.querynode | nindent 12 }}
          {{- end }}
          image: {{ include "tp-hawk-infra-querynode.image.registry" . }}{{"/"}}{{ include "tp-hawk-infra-querynode.image.repository" . }}{{"/"}}{{ .Values.images.querynode.image.name }}:{{ .Values.images.querynode.image.tag }}
          imagePullPolicy: {{ .Values.images.querynode.image.pullPolicy }}
          env:
            - name: unity.services.rest.host
              value: 0.0.0.0
            - name: unity.services.rest.port
              value: "9681"
            - name: JDK_JAVA_OPTIONS
              value: {{ .Values.javaOptions | quote }}
            - name: PROMETHEUS_SERVER_HOST
              value: prometheus-service
            - name: PROMETHEUS_SERVER_PORT
              value: "9090"
            - name: PROMETHEUS_SERVER_TLS_ENABLED
              value: "false"
            - name: PROMETHEUS_DISCOVERY_SERVICE_HOST
              value: prometheus-ds-service
            - name: PROMETHEUS_DISCOVERY_SERVICE_PORT
              value: "9000"
            - name: datasource_password
              valueFrom:
                secretKeyRef:
                  name: rtmon-postgres-credential
                  key: PGPASSWORD
            - name: PGHOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.global.cp.data.CP_DB_CONFIGURATION }}
                  key: DBHost
            - name: PGPORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.global.cp.data.CP_DB_CONFIGURATION }}
                  key: DBPort
            - name: waitForServices
              value: prometheus-ds-service:9000,prometheus-service:9090,$(PGHOST):$(PGPORT)
            - name: datasource_base_url
              value: "jdbc:postgresql://$(PGHOST):$(PGPORT)"
            - name: datasource_url
              value: "jdbc:postgresql://$(PGHOST):$(PGPORT)/{{ include "tp-hawk-infra-querynode.consts.hawkDbPrefix" . }}rtmon"
            - name: datasource_username
              value: {{ include "tp-hawk-infra-querynode.consts.hawkDbPrefix" . }}rtmonadm
            - name: HAWK_QUERYNODE_DATABASE_ENDPOINT_URL
              value: "$(PGHOST):$(PGPORT)"
            {{- if eq .Values.global.external.db_ssl_mode "verify-full" }}
            - name: datasource_tls_cacert_file
              value: {{ .Values.global.external.db_ssl_root_cert }}
            - name: DATASOURCE_TLS_SKIP_HOSTNAME_VERIFICATION
              value: "false"
            {{- end }}
            - name: METRIC_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: metric-token-query-secret
                  key: metric_auth_token
          {{- if .Values.global.cp.enableResourceConstraints }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          ports:
            - containerPort: 9681
              protocol: TCP
              name: rest-querynode
          readinessProbe:
            httpGet:
              path: /docs
              port: rest-querynode
              scheme: HTTP
            initialDelaySeconds: {{ .Values.querynode.readinessInitialDelaySeconds }}
            periodSeconds: {{ .Values.querynode.readinessPeriodSeconds }}
            timeoutSeconds: {{ .Values.querynode.readinessTimeoutSeconds }}
            failureThreshold: {{ .Values.querynode.readinessFailureThreshold }}
            successThreshold: {{ .Values.querynode.readinessSuccessThreshold }}
          livenessProbe:
            httpGet:
              path: /docs
              port: rest-querynode
              scheme: HTTP
            initialDelaySeconds: {{ .Values.querynode.livenessInitialDelaySeconds }}
            periodSeconds: {{ .Values.querynode.livenessPeriodSeconds }}
            timeoutSeconds: {{ .Values.querynode.livenessTimeoutSeconds }}
            failureThreshold: {{ .Values.querynode.livenessFailureThreshold }}
            successThreshold: {{ .Values.querynode.livenessSuccessThreshold }}
          volumeMounts:
            - name: store-vol
              mountPath: /private/tsc/certificates
              subPath: tsc/certificates
            - mountPath: /tmp
              name: tmpfs-1
            - mountPath: /redtail/querynode/data/
              name: tmpfs-2
            - mountPath: /redtail/tmp
              name: tmpfs-3
            - mountPath: /redtail/data/
              name: tmpfs-4

      volumes:
        - name: store-vol
          persistentVolumeClaim:
            claimName: {{ include "tp-hawk-infra-querynode.pvc-name" . }}
        - name: tmpfs-1
          emptyDir: {}
        - name: tmpfs-2
          emptyDir: {}
        - name: tmpfs-3
          emptyDir: {}
        - name: tmpfs-4
          emptyDir: {}
