# Copyright Â© 2025. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.

apiVersion: v2
name: bw-recipes
description: TIBCO Controlplane BusinessWorks Data Plane recipes
type: application
version: 1.13.0
appVersion: "1.13.0"
keywords:
  - tibco-platform
  - control-plane
annotations:
  app.helm.sh/component: control-plane
  app.helm.sh/name: bw-recipes
