# Copyright Â© 2023. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.

{{if .Values.httpIngress.enabled  -}}
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Values.httpIngress.name }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.httpIngress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.httpIngress.ingressClassName}}
  rules:
    - host: "{{ .Values.dns.vanity }}.{{ .Values.dns.domain }}"
      http:
        paths:
          - path: {{ .Values.httpIngress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.httpIngress.backend.serviceName }}
                port:
                  number: {{ .Values.httpIngress.backend.servicePort }}
{{- end -}}
