# Copyright Â© 2025. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "flogo-recipes.appName" . }}-cm
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flogo-recipes.labels" . | nindent 4 }}
data:
  version.json: |
    {
      "capabilityVersion": {{ .Chart.AppVersion | quote }},
      "minCPVersion": "1.14.0",
      "maxCPVersion": "",
      "releaseDate": {{ .Values.capabilities.flogo.releaseDate | quote }},
      "releaseNotes": {{ .Values.capabilities.flogo.releaseNotes | quote }},
      "minVersionRequiredForUpgrade": "1.4.0",
      "minDPVersion": {
        "dp-core-infrastructure": "1.12.0",
        "dp-configure-namespace": "1.7.0"
      }
    }
  package.json: |
    {
      "package": {
        "services": [
          {
            "name": "flogoprovisioner",
            "description": "Flogo Provisioner Service",
            "monitoringPriority": "essential"
          }
        ],
        "dependsOn": [
          {
            "version": [
              1,
              11,
              0
            ],
            "capabilityId": "INTEGRATIONCORE",
            "capabilityType": "INFRA"
          }
        ],
        "provisioningRoles": [
          "DEV_OPS"
        ],
        "serviceUrl": "http://flogoprovisioner:7816",
        "allowMultipleInstances": false,
        "capabilityResourceDependencies": [
          {
            "type": "Ingress Controller",
            "required": true,
            "resourceId": "INGRESS",
            "resourceType": "PLATFORM"
          }
        ]
      }
    }
  # Recipe copied from https://github.com/tibco/cicinfra-devops/blob/main/recipes/cp-platform-dev/DataPlane/poc/recipes/capabilities/flogo-capabilties.yaml
  recipe.yaml: |
    recipe:
      helmCharts:
        - name: flogoprovisioner
          namespace: ${NAMESPACE}
          version: "1.14.3"
          repository:
            chartMuseum:
              host: ${HELM_REPO}
          values:
            - content: |
                global:
                  cp:
                    logging:
                      fluentbit:
                        apps:
                          enabled: ${ENABLE_APPS_FLUENTBIT_SIDECAR}
                  flogoprovisioner:
                    image:
                      tag: 784-platform-1.14.0
                config:
                  APP_INIT_IMAGE_TAG: "51"
                  APP_HELMCHART_VERSION: "1.14.3"
                  INFRA_CP_PROXY_IMAGE_TAG: "291"
                publicApi:
                  ingress:
                    controllerName: ${INGRESS_CONTROLLER_NAME}
                    config:
                      className: ${INGRESS_CLASS_NAME}
                      pathPrefix: ${INGRESS_PATH_PREFIX}
                      fqdn: ${INGRESS_FQDN}
          flags:
            install: true
            createNamespace: false
            dependencyUpdate: true

---

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "flogo-recipes.appName" . }}-{{ randAlphaNum 4 | lower }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flogo-recipes.labels" . | nindent 4 }}
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 3600
  template:
    metadata:
      labels:
        {{- include "flogo-recipes.labels" . | nindent 8 }}
    spec:
      {{- if .Values.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      nodeSelector:
        kubernetes.io/os: linux
      imagePullSecrets:
        {{- if (include "flogo-recipes.container-registry.secret" .) }}
        - name: {{ include "flogo-recipes.container-registry.secret" . }}
        {{- end }}
      containers:
      - name: flogo
        image: {{ include "flogo-recipes.image.registry" .}}{{"/"}}{{ include "flogo-recipes.image.repository" .}}{{"/"}}{{ .Values.image.name }}:{{ .Values.image.tag}}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- with .Values.probes.startupProbe }}
        startupProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- if .Values.securityContext }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        {{- end }}
        {{- if $.Values.global.tibco.enableResourceConstraints }}
        resources:
          {{- toYaml .Values.scripts.resources | nindent 10 }}
        {{- end }}
        env:
        - name: CAPABILITY_NAME
          value: "flogo"
        - name: RECIPE_MOUNT_LOCATION
          value: "/opt/tibco/recipe"
        - name: RECIPE_TARGET_LOCATION
          value: "/private/tsc/config/capabilities/platform"
        - name: RECIPE_RELEASE_VERSION
          value: {{ .Chart.AppVersion | quote }}
        - name: SPACE_SEPARATED_UNSUPPORTED_RECIPE_VERSIONS
          value: ""
        - name: OVERWRITE_RECIPE
          value: {{ .Values.capabilities.flogo.overwriteRecipe | quote }}
        - name: IS_LATEST
          value: {{ .Values.capabilities.flogo.isLatest | quote }}
        volumeMounts:
        - name: {{ include "flogo-recipes.appName" . }}-vol
          mountPath: /opt/tibco/recipe
        - name: scripts-config-volume
          mountPath: /opt/tibco/scripts
        - name: store-vol
          mountPath: /private/tsc/config
          subPath: tsc/config
        - name: tmp-vol
          mountPath: /tmp
        command: ["sh"]
        args: ["-c", "/opt/tibco/scripts/run.sh"]
      restartPolicy: Never
      volumes:
        - name: {{ include "flogo-recipes.appName" . }}-vol
          configMap:
            name: {{ include "flogo-recipes.appName" . }}-cm
        - name: scripts-config-volume
          configMap:
            name: {{ include "flogo-recipes.appName" . }}-script
            defaultMode: 0777
        - name: store-vol
          persistentVolumeClaim:
            claimName: {{ include "flogo-recipes.pvc-name" . }}
        - name: tmp-vol
          emptyDir: {}
