# Copyright Â© 2025. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.

apiVersion: v2
name: bw5ce-utilities
version: "1.12.0"
appVersion: "1.12.0"
description: TIBCO CIC Global Provider -- BW5 Containers Utilities

