#
# Copyright © 2023-2026. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#
apiVersion: v2
name: tibco-developer-hub
description: A Helm chart for TIBCO® Developer Hub
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.15.14
appVersion: "1.15.0"
dependencies:
  - name: common
    repository: ""
    tags:
      - bitnami-common
    version: 2.x.x
  - condition: postgresql.enabled
    name: postgresql
    repository: ""
    version: 11.x.x
