# Copyright Â© 2025. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#
apiVersion: v2
name: tp-cp-integration-common
version: 1.13.0
appVersion: 1.13.0
description: TIBCO Platform integration prerequesites
dependencies:
  - name: fileserver
    version: "1.13.*"
    condition: fileserver.enabled
