#
# Copyright Â© 2023 - 2024. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#


{{/* all cluster roles are created at once during the deployment of the chart in the namespace */}}
{{- if .Values.global.tibco.rbac.infra }}
{{- if not .Values.global.tibco.useSingleNamespace }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "tibco-cp-base.globalResourceName" . }}
  labels:
    {{- include "tibco-cp-base.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["create", "get", "list", "patch", "update", "delete"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["create", "get", "list", "patch", "update", "delete"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["rolebindings", "roles"]
  verbs: ["create", "get", "list", "patch", "update", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["create", "get", "list", "patch", "update", "delete"]
- apiGroups: [""]
  resources: ["pods", "configmaps", "secrets"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["*"]
- apiGroups: ["cloud.tibco.com"]
  resources: ["tibcotunnelroutes", "tibcotunnelroutes/status"]
  verbs: ["*"]
{{- end -}}
{{- end -}}
