#
# Copyright Â© 2023 - 2024. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#

{{- $ext := .Values.global.external -}}
{{- $log := $ext.logserver -}}
{{- $audit := $ext.logserver -}}
{{- $logOK := and $log $log.password -}}
{{- $auditOK := and $audit $audit.password -}}
{{- if or $logOK $auditOK }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tibco-cp-base.otel.secret" .}}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tibco-cp-base.labels" . | nindent 4 }}
type: Opaque
data:
{{- if $logOK }}
  CP_LOGSERVER_PASSWORD: {{ $log.password | b64enc }}
{{- end }}
{{- if $auditOK }}
  CP_AUDITSERVER_PASSWORD: {{ $audit.password | b64enc }}
{{- end }}
{{- end }}
