# Copyright Â© 2025. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.

apiVersion: v2
name: tp-cp-integration-bw5
version: 1.5.2
appVersion: 1.5.0
description: TIBCO Platform Control Plane -- BW5 Integration
dependencies:
  - name: bw5-webserver
    version: "1.5.*"
    condition: bw5-webserver.enabled
