# Copyright Â© 2025. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.

apiVersion: v2
name: tp-cp-bw5ce-utilities
version: 1.12.3
appVersion: 1.12.0
description: TIBCO Platform Control Plane -- BW5 containers Utilities
dependencies:
  - name: bw5ce-utilities
    version: "1.12.*"
    condition: bw5ce-utilities.enabled
