# Copyright Â© 2025. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#
apiVersion: v2
name: flogo-webserver
version: 1.14.0
appVersion: "1.14.0"
description: Flogo webserver
keywords:
  - tibco-platform
  - control-plane
annotations:
  app.helm.sh/component: control-plane
  app.helm.sh/name: flogo-webserver