#
# Copyright Â© 2023 - 2024. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#

{{ if .Values.clusterIssuer.create -}}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cic-cert-subscription-scope-production-{{ .Values.httpIngress.name }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: cloud@tibco.com
    privateKeySecretRef:
      name: cic-cert-subscription-scope-production-{{ .Values.httpIngress.name }}
    solvers:
      - dns01:
          azureDNS:
            hostedZoneName: "{{ .Values.global.dnsSandboxSubdomain }}.{{ .Values.global.dnsGlobalTopDomain }}"
            resourceGroupName: "{{ .Values.global.azureSubscriptionDnsResourceGroup }}"
            subscriptionID: "{{ .Values.global.azureSubscriptionId }}"
            environment: AzurePublicCloud
            managedIdentity:
              clientID: "{{ .Values.global.azureAwiAsoDnsClientId }}"
{{- end }}