#
# Copyright Â© 2023 - 2024. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#

{{if .Values.storageClass.azurefile.enabled -}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.azurefile.name }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "{{ .Values.storageClass.azurefile.default }}"
provisioner: file.csi.azure.com
reclaimPolicy: {{ .Values.storageClass.azurefile.reclaimPolicy }}
allowVolumeExpansion: {{ .Values.storageClass.azurefile.allowVolumeExpansion }}
volumeBindingMode: {{ .Values.storageClass.azurefile.volumeBindingMode }}
{{- with .Values.storageClass.azurefile.mountOptions }}
mountOptions:
  {{- toYaml . | nindent 2 }}
{{- end }}
parameters:
{{- range $key, $value := .Values.storageClass.azurefile.parameters }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end -}}