#
# Copyright Â© 2024. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#
cp:
  ## This is used to delete the DB while Uninstalling the Chart. Default it is set to false so it will just take the backup of DB, data in DB will be retained as it is.
  ## If it is set to true then, it will take the DB backup and wipe-out the DB (i.e. It will clean the schema, database, users. )
  deleteDBOnUninstall: "false"

# Global section will apply to this chart and all of its subcharts.
global:
  tibco:
    region: "global"
    region_to_prefix: '{"TSC":{"global":""},"ADMIN":{"global":""}}'
    # Flag to enable or disable database jobs (upgrade and cleanup)
    # Set to false to disable DB script execution if you want to run scripts manually outside of the chart
    # Default value is true
    manageDbSchema: true
    rbac:
      # Flag to enable or disable creation of RBAC resources (ServiceAccount, Role, RoleBinding)
      # Set to false if you want to manage RBAC resources externally
      # Default value is true
      infra: true
    containerRegistry:
      url: ""
      username: ""
      password: ""
      repository: "tibco-platform-docker-prod"  # repository
    createNetworkPolicy: false
    networkPolicy:
      # Enable or disable the creation of cluster-wide network policies
      createClusterScopePolicies: true
      # Enable or disable the creation of internet-facing network policies
      createInternetScopePolicies: true
      # Network policies for access to the database, if no values are provided, the database policy will not be created
      database:
        CIDR: ""
        port: ""
      # Network policies for access to the Kubernetes API server, if no values are provided, the Kubernetes API server policy will not be created
      kubeApiServer:
        CIDR: ""
        port: ""
    controlPlaneInstanceId: ""
    cronjobs:
      disableProvisionInfraCapabilitiesJob: "false"
      disableGdprPurgeHistoryJob: "true"
      disableIdmCleanUpJob: "false"
      disableIdmNotifyCertificatesExpiryJob: "true"
    image_name:
      webserver: "core-web-server"
      orchestrator: "core-orchestrator"
      userSubscriptions: "core-user-subscriptions"
      cronjobs: "core-cronjobs"
      identityManagement: "core-identity-management"
      identityProvider: "core-identity-provider"
      pengine: "core-pengine"
      cpScripts: "core-cp-scripts"
    helm:
      url: "https://tibcosoftware.github.io"
      repo: "tp-helm-charts"
      username: ""
      password: ""
      pullLatestCharts: false
      certificateSecretName: ""
    logging:
      fluentbit:
        enabled: true
        image:
          name: "common-fluentbit"
          tag: 4.1.0
    check_dependencies:
      distroless_debian:
        name: "common-distroless-base-debian-debug"
        tag: 12.12
    self_hosted_deployment: true
    is_replica_region: false
    finops: "disable"
    db_ssl_root_cert_secretname: "db-ssl-root-cert"
    db_ssl_root_cert_filename: "db_ssl_root.cert"
  external:
    dnsDomain: ""
    db_host: ""
    db_master_writer_host: ""
    db_local_reader_host: ""
    db_name: ""
    db_port: ""
    db_username: ""
    db_password: ""
    db_secret_name: ""
    environment: "production"
    db_ssl_mode: "disable"
    fromAndReplyToEmailAddress: "not-set-yet"
    cronJobReportsEmailAlias: ""
    platformEmailNotificationCcAddresses: ""
    externalIdpRequestToAddresses: ""
    externalIdpRequestCcAddresses: ""
    cpEncryptionSecretName: "cporch-encryption-secret"
    cpEncryptionSecretKey: "CP_ENCRYPTION_SECRET"
    emailServerType: ""
    emailServer:
      ses:
        arn: ""
      smtp:
        server: ""
        port: "25"
        username: ""
        password: ""
      sendgrid:
        apiKey: ""
      graph:
        # Secret should contain all configuration details as either key-value pairs or as a single key containing configuration as a JSON map.
        # Expected keys: tenant_id, client_id, client_secret (alternative to private_key), private_key (alternative to client_secret), x509_cert (required if private_key provided).
        clientDetailsSecretName: "client-details-secret"
        # skipSentFolder: set to true, t, or 1 for even non-sensitive emails to skip the Sent folder.
        skipSentFolder: "false"
    adminInitialPassword: ""
    storage:
      pvcName: "control-plane-pvc"
    admin:
      email: ""
      firstname: ""
      lastname: ""
    clusterInfo:
      nodeCIDR: ""
      serviceCIDR: ""
      podCIDR: ""
  # Pod Security Context configuration
  # This configuration ensures that the pod is run with non-root privileges for enhanced security.
  # The user, group, and filesystem group IDs are all set to 1000.
  # The filesystem group change policy is set to "Always", meaning the filesystem group is always set to the fsGroup.
  # The seccomp (secure computing mode) profile is set to RuntimeDefault, which means it uses the default profile provided by the runtime.
  # The sysctls configuration allows the platform hybrid proxy to bind to low ports (below 1024) as a non-root user.
  # This is achieved by setting the 'net.ipv4.ip_unprivileged_port_start' sysctl to 0.
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    fsGroupChangePolicy: "Always"
    seccompProfile:
      type: RuntimeDefault

  containerSecurityContextTpcpcoreJob:
    # It specifies that privilege escalation is not allowed for security reasons.
    # Additionally, it drops all capabilities, which is a common security practice to minimize potential risks.
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - CAP_NET_RAW
        - ALL

checkPodDependencies:
  resources:
    requests:
      cpu: "10m"
      memory: "20Mi"
    limits:
      cpu: "30m"
      memory: "40Mi"
