# Copyright Â© 2024. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.

apiVersion: v2
name: tp-cp-eventprocessing-be
version: 1.12.2
appVersion: 1.12.0
description: TIBCO Platform Control Plane -- BE Addon
dependencies:
  - name: be-webserver
    version: "1.12.*"
    condition: be-webserver.enabled
