#
# Copyright Â© 2023 - 2024. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#


apiVersion: v2
name: hybrid-proxy
version: 1.14.0
appVersion: "1.14.0"
description: TIBCO Platform cp core bootstrap -- Hybrid Proxy operator
