# Copyright Â© 2026. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.

{{- if .Values.mcpserver.enabled }}
apiVersion: cloud.tibco.com/v1
kind: TibcoRoute
metadata:
  name: {{ include "tp-cp-flogo-mcpserver.consts.appName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flogo-webserver.shared.labels.standard" . | nindent 4 }}
spec:
  serviceName: {{ include "tp-cp-flogo-mcpserver.consts.appName" . }}
  env:
  - name: TSC_DNS_DOMAIN
    valueFrom:
      configMapKeyRef:
        name: {{ include "tp-control-plane-dnsdomain-configmap" . }}
        key: TSC_DNS_DOMAIN
  endpoints:
  - path: /flogo/mcp
    internalPath: /mcp
    port: 8085
    protocol: http
    proxies:
    - listener: virtual
      config: secure
      fqdn: "${TSC_DNS_DOMAIN}"
{{- end }}
