# Copyright Â© 2026. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.

apiVersion: v2
name: dp-flogo-app
description: Helm chart for Flogo application
type: application
version: 1.15.12
appVersion: "1.15.0"
