# Copyright © 2025. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.

{{ if .Values.vsCodeExtensionCardExtract }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "flogo-utilities.fullname" . }}-vscode-extension-card-{{ randAlphaNum 4 | lower }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flogo-utilities.labels" . | nindent 4 }}
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 3600  # Cleanup of jobs from key/value store after 100 sec
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "flogo-utilities.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      {{- with $.Values.podSecurityContext }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      {{- end }}
      {{- if (include "flogo-utilities.container-registry.secret" .) }}
      imagePullSecrets:
        - name: {{ include "flogo-utilities.container-registry.secret" . }}
      {{- end }}
      containers:
        - name: card-extractor
          image: {{ include "flogo-utilities.image.registry" .}}{{"/"}}{{ include "flogo-utilities.infra.image.repository" .}}{{"/"}}{{ $.Values.debug.image.name }}:{{ $.Values.debug.image.tag }}
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          {{- with $.Values.probes.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $.Values.securityContext }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          {{- end }}
          {{- if $.Values.global.tibco.enableResourceConstraints }}
          resources:
            {{- toYaml $.Values.scripts.resources | nindent 12 }}
          {{- end }}
          command:
            - "sh"
            - "-c"
            - |
              basePath="/downloads/tools/flogo-vscode-extension/"
              # Remove existing extracted flogo vscode extensions
              rm -rf ${basePath}*
              mkdir -p ${basePath}
              cd /downloads/tools/flogo-vscode-extension
              
              # Generate download json file for UI
               finalStr=$finalStr"["
                  finalStr=$finalStr"   {"
                  finalStr=$finalStr"   \"Name\": \"TIBCO Flogo® Extension for Visual Studio Code\","
                  finalStr=$finalStr"   \"Description\": \"Using TIBCO Flogo® Extension for Visual Studio Code, you can accelerate TIBCO Flogo® application development by tapping into the robust Microsoft Visual Studio Code ecosystem. Design, build, and test Flogo® applications locally in a Visual Studio Code IDE. Deploy anywhere including on-premise, in private or public cloud (seamlessly using the new TIBCO® Platform) or devices.\","
                  finalStr=$finalStr"   \"LearnMoreLink\": \"https://docs.tibco.com/products/tibco-flogo-extension-for-visual-studio-code-latest\","
                  finalStr=$finalStr"   \"RedirectLink\": \"https://www.tibco.com/downloads/11810\","
                  finalStr=$finalStr"   \"BuildDate\":\"$(date "+%Y-%m-%dT%H:%M:%S%Z")\""
                  finalStr=$finalStr"   }"
              finalStr=$finalStr"]"

              echo $finalStr > flogo_vscode_extension_download.json
              cat flogo_vscode_extension_download.json
          volumeMounts:
            - name: shared-vol
              mountPath: {{ $.Values.toolsMountPath }}
              subPath: {{ $.Values.toolsSubPath }}
            - name: tmp-vol
              mountPath: /tmp
      volumes:
        - name: shared-vol
          persistentVolumeClaim:
            claimName: {{ include "flogo-utilities.pvc-name" . }}
        - emptyDir: {}
          name: tmp-vol
        {{- if (include "flogo-utilities.container-registry.secret" .) }}
        - name: container-registry-secret
          secret:
            secretName: {{ include "flogo-utilities.container-registry.secret" . }}
        {{- end }}
{{- end }}

