#
# Copyright (c) 2025. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#

apiVersion: v1
kind: Secret
metadata:
  name: cp-license-file-secret
type: Opaque
data:
  {{- range $filename, $content := .Values.global.cp.dataplane.licenseFiles }}
  {{ $filename }}: {{ $content | quote }}
  {{- end }}
