#
# Copyright Â© 2023 - 2024. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#

{{ if and .Values.collector.enabled .Values.collector.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "jaeger.collector.serviceAccountName" . }}
  labels:
    {{- include "jaeger.collector.labels" . | nindent 4 }}
    app.kubernetes.io/component: collector
  {{- with .Values.collector.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.collector.serviceAccount.automountServiceAccountToken }}
{{- end -}}
