# Copyright Â© 2024. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.

apiVersion: v2
name: dp-bwce-app
description: A Helm chart for BWCE application
type: application
version: 1.6.5
appVersion: "1.6.0"
