#
# Copyright Â© 2023 - 2024. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#
apiVersion: v2
name: o11yservice
version: 1.2.33
appVersion: "1.2.0"
description: A helm chart for o11y service
