#
# Copyright Â© 2023 - 2024. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#


global:
  tibco:
    dataPlaneId: "abcd"
    subscriptionId: "sub1"
    #[optional] Create an image pull secret <dpId> with this creds
    containerRegistry:
      url: "reldocker.tibco.com" 
      # username: ""
      # password: ""
      # email: "tibco-plt@tibco.com"