# Copyright Â© 2025. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.

{{ if .Values.bwCleanupJob }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "bwce-utilities.fullname" . }}-bw-cleanup-{{ randAlphaNum 4 | lower }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
  labels:
    {{- include "bwce-utilities.labels" . | nindent 4 }}
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 3600  # Cleanup of jobs from key/value store after 100 sec
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "bwce-utilities.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      # serviceAccountName: {{ include "bwce-utilities.service-account-name" . }}
      {{- with $.Values.podSecurityContext }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      {{- end }}
      containers:
        - name: delete-cleanup
          image: {{ include "bwce-utilities.image.registry" .}}{{"/"}}{{ include "bwce-utilities.infra.image.repository" .}}{{"/"}}{{ $.Values.debug.image.name }}:{{ $.Values.debug.image.tag }}
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          {{- with $.Values.probes.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $.Values.securityContext }}
          securityContext:
          {{- toYaml $.Values.securityContext | nindent 12 }}
          {{- end }}
          {{- if $.Values.global.tibco.enableResourceConstraints }}
          resources:
          {{- toYaml $.Values.scripts.resources | nindent 12 }}
          {{- end }}
          command:
            - "sh"
            - "-c"
            - |
              rm -rf /downloads/tools/bwce-studio
              echo "Cleanup of BWCE Studio versions completed."
              rm -rf /usr/share/nginx/html/bw-contribution
              echo "Cleanup of BWCE Plugins completed."
              rm -rf /usr/share/nginx/html/bwce
              echo "Cleanup of BWCE Buildtypes completed."
          volumeMounts:
            - name: shared-vol
              mountPath: {{ $.Values.toolsMountPath }}
              subPath: {{ $.Values.toolsSubPath }}
            - name: shared-vol
              mountPath: {{ $.Values.volumes.plugins.mountPath }}
              subPath: {{ $.Values.volumes.plugins.subPath }}
      volumes:
        - name: shared-vol
          persistentVolumeClaim:
            claimName: {{ include "bwce-utilities.pvc-name" . }}
{{- if (include "bwce-utilities.container-registry.secret" .) }}
      imagePullSecrets:
        - name: {{ include "bwce-utilities.container-registry.secret" . }}
{{- end }}
{{- end }}
