apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "tp-provisioner-agent.consts.appName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "tp-provisioner-agent.shared.labels.standard" . | nindent 4 }}
  annotations:
    ingress.kubernetes.io/path-rewrite: "/tibco/agent/infra/provisioner-agent/(.*) /\\1"
spec:
  ingressClassName: tibco-dp-{{ .Values.global.tibco.dataPlaneId}}
  rules:
  - host: {{ tpl .Values.global.dpUrl.host . }}
    http:
      paths:
      - pathType: Prefix
        path: /tibco/agent/infra/provisioner-agent/
        backend:
          service:
            name: {{ include "tp-provisioner-agent.consts.appName" . }}
            port:
              number: 80
  - host: "cpdpproxy" # tibtunnel probes the provisioner agent via haproxy hence the host is the HAProxy service name.
    http:
      paths:
      - pathType: Prefix
        path: /tibco/agent/infra/provisioner-agent/
        backend:
          service:
            name: {{ include "tp-provisioner-agent.consts.appName" . }}
            port:
              number: 80