#
# Copyright Â© 2023 - 2025. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#

apiVersion: v2
name: tibco-cp-addon-eventprocessing
description: TIBCO Platform chart for BE addon
type: application
version: 1.15.0-alpha.4
appVersion: "1.15.0"
keywords:
  - tibco-platform
  - platform
  - eventprocessing
  - addon
annotations:
  app.helm.sh/component: control-plane
  app.helm.sh/name: tibco-cp-addon-eventprocessing
dependencies:
  - name: tp-cp-eventprocessing-be
    version: "1.15.*"
    condition: tp-cp-eventprocessing-be.enabled
    tags:
      - be
