#
# Copyright Â© 2023-2026. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.

apiVersion: v2
name: tibcohub-recipes
description: TIBCO Developer Hub Data Plane Recipes
home: https://github.com/tibco/tp-dev-hub.git
type: application
version: 1.15.0
appVersion: "1.15.0"
keywords:
  - tibco-platform
  - control-plane
maintainers:
  - name: TIBCO CIC Compute Dev Team
    email: compute-dev@tibco.com
annotations:
  app.helm.sh/component: control-plane
  app.helm.sh/name: tibcohub-recipes
