# Copyright Â© 2023. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.

apiVersion: v2
name: flogoprovisioner
version: 1.2.11
appVersion: "1.2.0"
description: TIBCO Platform Dataplane Capabilty -- Flogo Provisioner
home: https://github.com/tibco/tp-iapp-flogo-provisioner.git
icon: https://pbs.twimg.com/profile_images/1064638558110007296/K6HqaXwh_400x400.jpg
maintainers:
  - name: TIBCO Platform Dev Team
    email: compute-dev@tibco.com
