#
# Copyright Â© 2023 - 2025. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#


apiVersion: v2
name: tp-cp-infra
version: 1.13.0
appVersion: 1.13.0
description: TIBCO Platform Control Plane Infra chart
