# Copyright (c) 2023-2025. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#
top: infra/hawkconsole
# latest is first in versions.json
files:
  infra/hawkconsole/versions.json: |
    [
      {
        "capabilityVersion": "1.13.0",
        "minCPVersion": "1.5.0",
        "maxCPVersion": "",
        "releaseDate": "2025/02/26",
        "releaseNotes": "Enhancements, Bug fixes, etc.",
        "minVersionRequiredForUpgrade": "1.4.0",
        "minDPVersion": {
          "dp-core-infrastructure": "1.4.0",
          "dp-configure-namespace": "1.4.0"
        }
      },
      {
        "capabilityVersion": "1.10.0",
        "minCPVersion": "1.5.0",
        "maxCPVersion": "",
        "releaseDate": "2025/02/26",
        "releaseNotes": "Enhancements, Bug fixes, etc.",
        "minVersionRequiredForUpgrade": "1.4.0",
        "minDPVersion": {
          "dp-core-infrastructure": "1.4.0",
          "dp-configure-namespace": "1.4.0"
        }
      },
      {
        "capabilityVersion": "1.11.0",
        "minCPVersion": "1.5.0",
        "maxCPVersion": "",
        "releaseDate": "2025/02/26",
        "releaseNotes": "Enhancements, Bug fixes, etc.",
        "minVersionRequiredForUpgrade": "1.4.0",
        "minDPVersion": {
          "dp-core-infrastructure": "1.4.0",
          "dp-configure-namespace": "1.4.0"
        }
      },
      {
        "capabilityVersion": "1.12.0",
        "minCPVersion": "1.5.0",
        "maxCPVersion": "",
        "releaseDate": "2025/02/26",
        "releaseNotes": "Enhancements, Bug fixes, etc.",
        "minVersionRequiredForUpgrade": "1.4.0",
        "minDPVersion": {
          "dp-core-infrastructure": "1.4.0",
          "dp-configure-namespace": "1.4.0"
        }
      },
      {
        "capabilityVersion": "1.7.0",
        "minCPVersion": "1.5.0",
        "maxCPVersion": "",
        "releaseDate": "2025/02/26",
        "releaseNotes": "Enhancements, Bug fixes, etc.",
        "minVersionRequiredForUpgrade": "1.4.0",
        "minDPVersion": {
          "dp-core-infrastructure": "1.4.0",
          "dp-configure-namespace": "1.4.0"
        }
      },
      {
        "capabilityVersion": "1.9.0",
        "minCPVersion": "1.5.0",
        "maxCPVersion": "",
        "releaseDate": "2025/02/26",
        "releaseNotes": "Enhancements, Bug fixes, etc.",
        "minVersionRequiredForUpgrade": "1.4.0",
        "minDPVersion": {
          "dp-core-infrastructure": "1.4.0",
          "dp-configure-namespace": "1.4.0"
        }
      }
    ]
  infra/hawkconsole/1.13.0/recipe.yaml: |
    recipe:
      helmCharts:
        - name: tp-dp-hawk-console
          namespace: ${NAMESPACE}
          version: "1.13.15"
          repository:
            chartMuseum:
              host: ${HELM_REPO}
          values:
            - content: |
                hawkconsole:
                  readinessFailureThreshold: 10
                  readinessInitialDelaySeconds: 12
                  readinessPeriodSeconds: 15
                  readinessTimeoutSeconds: 10
                  livenessFailureThreshold: 10
                  livenessInitialDelaySeconds: 15
                  livenessPeriodSeconds: 15
                  livenessTimeoutSeconds: 10
                  javaOptions: "-Xms1g -Xmx3g"
                  subscription:
                    interval:
                      bw5: 60000
                      be: 60000
                      sys: 60000
                      o11y: 60000
                  fileupload:
                    fileSizeLimit: 30MB
                    requestSizeLimit: 32MB
                resources:
                  requests:
                    cpu: 200m
                    memory: 1024Mi
                  limits:
                    cpu: 1000m
                    memory: 3072Mi                
          flags:
            install: true
            createNamespace: false
            dependencyUpdate: true
    
  infra/hawkconsole/1.13.0/package.json: |
    {
      "package": {
        "services": [
          {
            "name": "tp-dp-hawk-console",
            "description": "Hawk Console Service",
            "monitoringPriority": "essential"
          },
          {
            "name": "tp-msg-gateway",
            "description": "Messaging CT Gateway Services",
            "monitoringPriority": "essential"
          }
        ],
        "dependsOn": [],
        "provisioningRoles": [
          "DEV_OPS"
        ],
        "allowMultipleInstances": false,
        "capabilityResourceDependencies": []
      }
    }

  infra/hawkconsole/1.12.0/recipe.yaml: |
    recipe:
      helmCharts:
        - name: tp-dp-hawk-console
          namespace: ${NAMESPACE}
          version: "1.12.9"
          repository:
            chartMuseum:
              host: ${HELM_REPO}
          values:
            - content: |
                hawkconsole:
                  readinessFailureThreshold: 10
                  readinessInitialDelaySeconds: 12
                  readinessPeriodSeconds: 15
                  readinessTimeoutSeconds: 10
                  livenessFailureThreshold: 10
                  livenessInitialDelaySeconds: 15
                  livenessPeriodSeconds: 15
                  livenessTimeoutSeconds: 10
                  javaOptions: "-Xms1g -Xmx3g"
                  subscription:
                    interval:
                      bw5: 60000
                      be: 60000
                      sys: 60000
                      o11y: 60000
                  fileupload:
                    fileSizeLimit: 30MB
                    requestSizeLimit: 32MB
                resources:
                  requests:
                    cpu: 200m
                    memory: 1024Mi
                  limits:
                    cpu: 1000m
                    memory: 3072Mi                
          flags:
            install: true
            createNamespace: false
            dependencyUpdate: true
  infra/hawkconsole/1.12.0/package.json: |
    {
      "package": {
        "services": [
          {
            "name": "tp-dp-hawk-console",
            "description": "Hawk Console Service",
            "monitoringPriority": "essential"
          },
          {
            "name": "tp-msg-gateway",
            "description": "Messaging CT Gateway Services",
            "monitoringPriority": "essential"
          }
        ],
        "dependsOn": [],
        "provisioningRoles": [
          "DEV_OPS"
        ],
        "allowMultipleInstances": false,
        "capabilityResourceDependencies": []
      }
    }
  infra/hawkconsole/1.11.0/recipe.yaml: |
    recipe:
      helmCharts:
        - name: tp-dp-hawk-console
          namespace: ${NAMESPACE}
          version: "1.11.15"
          repository:
            chartMuseum:
              host: ${HELM_REPO}
          values:
            - content: |
                hawkconsole:
                  readinessFailureThreshold: 10
                  readinessInitialDelaySeconds: 12
                  readinessPeriodSeconds: 15
                  readinessTimeoutSeconds: 10
                  livenessFailureThreshold: 10
                  livenessInitialDelaySeconds: 15
                  livenessPeriodSeconds: 15
                  livenessTimeoutSeconds: 10
                  javaOptions: "-Xms1g -Xmx3g"
                  subscription:
                    interval:
                      bw5: 60000
                      be: 60000
                      sys: 60000
                      o11y: 60000
                  fileupload:
                    fileSizeLimit: 30MB
                    requestSizeLimit: 32MB
                resources:
                  requests:
                    cpu: 200m
                    memory: 1024Mi
                  limits:
                    cpu: 1000m
                    memory: 3072Mi                
          flags:
            install: true
            createNamespace: false
            dependencyUpdate: true
  infra/hawkconsole/1.11.0/package.json: |
    {
      "package": {
        "services": [
          {
            "name": "tp-dp-hawk-console",
            "description": "Hawk Console Service",
            "monitoringPriority": "essential"
          },
          {
            "name": "tp-msg-gateway",
            "description": "Messaging CT Gateway Services",
            "monitoringPriority": "essential"
          }
        ],
        "dependsOn": [],
        "provisioningRoles": [
          "DEV_OPS"
        ],
        "allowMultipleInstances": false,
        "capabilityResourceDependencies": []
      }
    }
  infra/hawkconsole/1.10.0/recipe.yaml: |
    recipe:
      helmCharts:
        - name: tp-dp-hawk-console
          namespace: ${NAMESPACE}
          version: "1.10.7"
          repository:
            chartMuseum:
              host: ${HELM_REPO}
          values:
            - content: |
                image:
                  tag: "1.10.0.7"
                hawkconsole:
                  readinessFailureThreshold: 10
                  readinessInitialDelaySeconds: 12
                  readinessPeriodSeconds: 15
                  readinessTimeoutSeconds: 10
                  livenessFailureThreshold: 10
                  livenessInitialDelaySeconds: 15
                  livenessPeriodSeconds: 15
                  livenessTimeoutSeconds: 10
                  javaOptions: "-Xms1g -Xmx3g"
                  subscription:
                    interval:
                      bw5: 60000
                      be: 60000
                      sys: 60000
                      o11y: 60000
                  fileupload:
                    fileSizeLimit: 30MB
                    requestSizeLimit: 32MB
                resources:
                  requests:
                    cpu: 200m
                    memory: 1024Mi
                  limits:
                    cpu: 1000m
                    memory: 3072Mi                
          flags:
            install: true
            createNamespace: false
            dependencyUpdate: true
  infra/hawkconsole/1.10.0/package.json: |
    {
      "package": {
        "services": [
          {
            "name": "tp-dp-hawk-console",
            "description": "Hawk Console Service",
            "monitoringPriority": "essential"
          },
          {
            "name": "tp-msg-gateway",
            "description": "Messaging CT Gateway Services",
            "monitoringPriority": "essential"
          }
        ],
        "dependsOn": [],
        "provisioningRoles": [
          "DEV_OPS"
        ],
        "allowMultipleInstances": false,
        "capabilityResourceDependencies": []
      }
    }
  infra/hawkconsole/1.9.0/recipe.yaml: |
    recipe:
      helmCharts:
        - name: tp-dp-hawk-console
          namespace: ${NAMESPACE}
          version: "1.9.28"
          repository:
            chartMuseum:
              host: ${HELM_REPO}
          values:
            - content: |
                image:
                  tag: "1.9.0.28"
                hawkconsole:
                  readinessFailureThreshold: 10
                  readinessInitialDelaySeconds: 12
                  readinessPeriodSeconds: 15
                  readinessTimeoutSeconds: 10
                  livenessFailureThreshold: 10
                  livenessInitialDelaySeconds: 15
                  livenessPeriodSeconds: 15
                  livenessTimeoutSeconds: 10
                  javaOptions: "-Xms1g -Xmx3g"
                  subscription:
                    interval:
                      bw5: 60000
                      be: 60000
                      sys: 60000
                      o11y: 60000
                  fileupload:
                    fileSizeLimit: 30MB
                    requestSizeLimit: 32MB
                resources:
                  requests:
                    cpu: 200m
                    memory: 1024Mi
                  limits:
                    cpu: 1000m
                    memory: 3072Mi                
          flags:
            install: true
            createNamespace: false
            dependencyUpdate: true
  infra/hawkconsole/1.9.0/package.json: |
    {
      "package": {
        "services": [
          {
            "name": "tp-dp-hawk-console",
            "description": "Hawk Console Service",
            "monitoringPriority": "essential"
          },
          {
            "name": "tp-msg-gateway",
            "description": "Messaging CT Gateway Services",
            "monitoringPriority": "essential"
          }
        ],
        "dependsOn": [],
        "provisioningRoles": [
          "DEV_OPS"
        ],
        "allowMultipleInstances": false,
        "capabilityResourceDependencies": []
      }
    }
  infra/hawkconsole/1.7.0/recipe.yaml: |
    recipe:
      helmCharts:
        - name: tp-dp-hawk-console
          namespace: ${NAMESPACE}
          version: "1.7.19"
          repository:
            chartMuseum:
              host: ${HELM_REPO}
          values:
            - content: |
                image:
                  tag: "1.7.0.19"
                hawkconsole:
                  readinessFailureThreshold: 10
                  readinessInitialDelaySeconds: 12
                  readinessPeriodSeconds: 15
                  readinessTimeoutSeconds: 10
                  livenessFailureThreshold: 10
                  livenessInitialDelaySeconds: 15
                  livenessPeriodSeconds: 15
                  livenessTimeoutSeconds: 10
                resources:
                  requests:
                    cpu: 200m
                    memory: 1024Mi
                  limits:
                    cpu: 1000m
                    memory: 3072Mi                
          flags:
            install: true
            createNamespace: false
            dependencyUpdate: true
  infra/hawkconsole/1.7.0/package.json: |
    {
      "package": {
        "services": [
          {
            "name": "tp-dp-hawk-console",
            "description": "Hawk Console Service",
            "monitoringPriority": "essential"
          },
          {
            "name": "tp-msg-gateway",
            "description": "Messaging CT Gateway Services",
            "monitoringPriority": "essential"
          }
        ],
        "dependsOn": [],
        "provisioningRoles": [
          "DEV_OPS"
        ],
        "allowMultipleInstances": false,
        "capabilityResourceDependencies": []
      }
    }
