#
# Copyright Â© 2023 - 2024. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#

apiVersion: v2
name: tp-cp-recipes
description: TIBCO Platform recipe chart

type: application
version: 1.3.174
appVersion: "1.3.0-HF2"
keywords:
  - tibco-platform
  - platform
  - recipes
annotations:
  app.helm.sh/component: control-plane
  app.helm.sh/name: tp-cp-recipes
dependencies:
  - name: tp-cp-infra-recipes
    version: "1.3.60"
    repository: alias:tibco-platform
  - name: tp-cp-bwce-recipes
    version: "1.3.35"
    repository: alias:tibco-platform
  - name: tp-cp-flogo-recipes
    version: "1.3.30"
    repository: alias:tibco-platform
  - name: tp-cp-tibcohub-recipes
    version: "1.3.20"
    repository: alias:tibco-platform
  - name: dp-oauth2proxy-recipes
    version: "1.3.19"
    repository: alias:tibco-platform
  - name: tp-cp-servicemesh-recipes
    version: "1.3.5"
    repository: alias:tibco-platform
  - name: tp-cp-hawk-console-recipes
    version: "1.3.26"
    repository: alias:tibco-platform
