# Copyright Â© 2026. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.

{{ $fullName := include "bw5provisioner.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bw5provisioner.fullname" . }}
  labels:
    {{- include "bw5provisioner.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "bw5provisioner.selectorLabels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
        checksum/config: {{ include (print $.Template.BasePath "/serviceconfigmap.yaml") . | sha256sum }}
      labels:
        {{- include "bw5provisioner.selectorLabels" . | nindent 8 }}
        networking.platform.tibco.com/kubernetes-api: enable
        networking.platform.tibco.com/internet-web-egress: enable
        networking.platform.tibco.com/userApps: enable
    spec:
      imagePullSecrets:
      - name: {{ .Values.global.cp.containerRegistry.secret }}
      {{- if .Values.global.cp.resources.serviceaccount.serviceAccountName }}
      serviceAccountName: {{ .Values.global.cp.resources.serviceaccount.serviceAccountName }}
      {{- end }}
      {{- if .Values.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: server
            - containerPort: {{ .Values.publicApiService.port }}
              name: publicapiserver
          {{- if .Values.securityContext.bw5provisioner }}
          securityContext:
            {{- toYaml .Values.securityContext.bw5provisioner | nindent 12 }}
          {{- end }}
          image: {{ include "bw5provisioner.image.registry" .}}{{"/"}}{{ include "bw5provisioner.image.repository" .}}{{"/"}}tp-bw5-provisioner:{{ .Values.global.bw5provisioner.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: v1/liveness
              port: {{ .Values.service.port }}
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
          {{- if .Values.global.cp.enableResourceConstraints }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          env:
            {{- range $filename, $content :=  .Values.config }}
            - name: {{ $filename }}
              valueFrom:
                configMapKeyRef:
                  name: {{ $fullName }}-serviceconfig
                  key: {{ $filename }}
            {{- end }}
            - name: DATAPLANE_ID
              value: {{ .Values.global.cp.dataplaneId }}
            - name: INSTANCE_ID
              value: {{ .Values.global.cp.instanceId }}
            - name: BW5_PROVISIONER_BUILD
              value: "{{ .Values.global.bw5provisioner.image.tag }}"
            - name: SERVER_PORT
              value: "{{ .Values.service.port }}"
            - name: PUBLIC_API_SERVER_PORT
              value: "{{ .Values.publicApiService.port }}"
            - name: CP_DOMAIN
              value: {{ include "bw5provisioner.cp.domain" . }}
            - name: CHART_VERSION
              value: {{ .Chart.Version }}
            - name: CHART_APP_VERSION
              value: {{ .Chart.AppVersion }}
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: IMAGE_PULL_SECRET
              value: {{ .Values.global.cp.containerRegistry.secret }}
            - name: APP_INIT_SOURCE_REGISTRY
              value: {{ include "bw5provisioner.image.registry" .}}{{"/"}}{{ include "bw5provisioner.appinit.image.repository" .}}{{"/"}}
            - name: SOURCE_REGISTRY
              value: {{ include "bw5provisioner.image.registry" .}}{{"/"}}{{ include "bw5provisioner.image.repository" .}}{{"/"}}
            - name: LOGGING_FLUENT_BIT_ENABLED
              value: "{{ .Values.global.cp.logging.fluentbit.apps.enabled }}"
            - name: FLUENT_BIT_SIDECAR_IMAGE
              value: {{ include "bw5provisioner.image.registry" .}}{{"/"}}{{ include "bw5provisioner.appinit.image.repository" .}}{{"/"}}common-fluentbit:{{ .Values.global.cp.logging.fluentbit.image.tag }}
            - name: ACTIVATION_SERVICE_URL
              value: {{ .Values.global.cp.resources.activationServer.url | quote }}
            - name: OAUTH2_PROXY_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "bw5provisioner.secrets.oauth2clientcreds" .}}
                  key: clientId
            - name: OAUTH2_PROXY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "bw5provisioner.secrets.oauth2clientcreds" .}}
                  key: clientSecret
            - name: AUTHORIZATION_SERVER_URL
              value: "https://{{ .Values.global.cp.cpHostname}}"
            - name: DATAPLANE_HOST
            {{- if .Values.global.cp.resources.gatewayapi.gatewayHostOrDomainName }}
              value: "{{ .Values.global.cp.resources.gatewayapi.gatewayHostOrDomainName }}"
            {{- else }}
              value: "{{ .Values.global.cp.resources.ingress.fqdn }}"
            {{- end }}
            - name: PATH_PREFIX
              value: "{{ .Values.publicApi.config.pathPrefix }}"
            - name: OTEL_METRICS_SERVICE_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "bw5provisioner.o11yservice.configmap" . }}
                  key: otel-recv-metrics-name
                  optional: true
            - name: OTEL_METRICS_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "bw5provisioner.o11yservice.configmap" . }}
                  key: otel-recvservice-port
                  optional: true
            - name: OTEL_TRACES_SERVICE_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "bw5provisioner.o11yservice.configmap" . }}
                  key: otel-recv-traces-name
                  optional: true
            - name: OTEL_TRACES_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "bw5provisioner.o11yservice.configmap" . }}
                  key: otel-recvservice-port
                  optional: true
          volumeMounts:
            - name: logs-share
              mountPath: /tmp/logs/share
            - name: tmp-workspace
              mountPath: /tmp/bw5-provisioner/workspace
        {{- if .Values.global.cp.logging.fluentbit.enabled }}
        - name: fluent-bit
          image: {{ include "bw5provisioner.image.registry" .}}{{"/"}}{{ include "bw5provisioner.appinit.image.repository" .}}{{"/"}}common-fluentbit:{{ .Values.global.cp.logging.fluentbit.image.tag }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          {{- if .Values.global.cp.logging.fluentbit.securityContext }}
          securityContext:
            {{- toYaml .Values.global.cp.logging.fluentbit.securityContext | nindent 12 }}
          {{- end }}
          {{- with .Values.global.cp.logging.fluentbit.probes.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.global.cp.enableResourceConstraints }}
          {{- with .Values.global.cp.logging.fluentbit.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: CONTAINER_NAME
              value: {{ .Chart.Name }}
          volumeMounts:
            - name: logs-share
              mountPath: /var/log/pods
            - name: fluent-bit-config
              mountPath: /fluent-bit/etc/
        {{- end }}
      volumes:
        - emptyDir: {}
          name: tmp-workspace
        - emptyDir: {}
          name: logs-share
        {{- if .Values.global.cp.logging.fluentbit.enabled }}
        - name: fluent-bit-config
          configMap:
            name: {{ include "bw5provisioner.fullname" . }}-fluentbit-config
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
