# Copyright Â© 2024. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.

apiVersion: v2
name: dp-bwce-mon
version: 1.13.1
appVersion: "1.13.0"
description: TIBCO Platform Dataplane Capabilty -- BWCE Monitoring
