# Copyright Â© 2026. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#
apiVersion: v2
name: flogo-recipes
description: Flogo data plane recipes
type: application
version: 1.15.0
appVersion: "1.15.0"
keywords:
  - tibco-platform
  - control-plane
annotations:
  app.helm.sh/component: control-plane
  app.helm.sh/name: flogo-recipes
