#
# Copyright Â© 2025. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#


apiVersion: v1
kind: Service
metadata:
  name: {{ include "tp-dp-proxy.consts.svcName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tp-dp-proxy.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "tp-dp-proxy.selectorLabels" . | nindent 4 }}
  ports:
  - name: server
    port: 80
    protocol: TCP
    targetPort: server
  sessionAffinity: None
  type: ClusterIP