#
# Copyright Â© 2023 - 2024. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#

controller:
  service:
    type: NodePort
    ports:
      8000: 10000
      8001: 10001
