# Copyright Â© 2025. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tibcohub-recipes.consts.appName" . }}-tibcohub
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tibcohub-recipes.labels" . | nindent 4 }}
data:
  version.json: |
    {
      "capabilityVersion": "1.14.0",
      "minCPVersion": "1.12.0",
      "maxCPVersion": "",
      "releaseDate": {{ .Values.capabilities.tibcohub.releaseDate | quote }},
      "releaseNotes": {{ .Values.capabilities.tibcohub.releaseNotes | quote }},
      "minVersionRequiredForUpgrade": "1.4.0",
      "minRollbackVersion": "1.10.0",
      "minDPVersion": {
        "dp-core-infrastructure": "1.12.0",
        "dp-configure-namespace": "1.7.0"
      }
    }
  package.json: |
    {
      "package": {
        "services": [
          {
            "name": "postgresql",
            "description": "Postgres Database",
            "monitoringPriority": "optional"
          },
          {
            "name": "tibco-developer-hub",
            "description": "NodeJs backend and UI hosting service",
            "monitoringPriority": "essential"
          }
        ],
        "provisioningRoles": [
          "DEV_OPS"
        ],
        "serviceUrl": "http://tibco-developer-hub:7007",
        "allowMultipleInstances": false,
        "capabilityResourceDependencies": [
          {
            "type": "Ingress Controller",
            "required": true,
            "resourceId": "INGRESS",
            "resourceType": "PLATFORM"
          },
          {
            "type": "Storage Class",
            "required": true,
            "resourceId": "STORAGE",
            "resourceType": "PLATFORM",
            "otherResourceIds": [ "DBCONFIG" ]
          },
          {
            "type": "Database Resource",
            "required": true,
            "resourceId": "DBCONFIG",
            "resourceType": "PLATFORM",
            "otherResourceIds": [ "STORAGE" ]
          }
        ]
      }
    }

  recipe.yaml: |
    recipe:
      helmCharts:
      - name: tibco-developer-hub
        version: "1.14.5"
        namespace: ${NAMESPACE}
        repository:
          chartMuseum:
            host: ${HELM_REPO}
        values:
          - content: |
              baseUrlKeyPath: backstage.appConfig.app.baseUrl
              backstage:
                appConfig:
                  app:
                    baseUrl: ${PUBLIC_URL}
                  backend:
                    baseUrl: ${PUBLIC_URL}
                # only if user provides a secrets reference
                # extraEnvVarsSecrets:
                #  - ${SECRETS_NAME}
              postgresql:
                enabled: true
              ingress:
                enabled: true
                className: ${INGRESS_CLASSNAME}
                host: ${HOSTNAME}
              publicApi:
                  ingress:
                    controllerName: ${INGRESS_CONTROLLER_NAME}
                    config:
                      className: ${INGRESS_CLASS_NAME}
                      fqdn: ${INGRESS_FQDN}
        flags:
          install: true
          createNamespace: false
          dependencyUpdate: true

---

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "tibcohub-recipes.consts.appName" . }}-tibcohub-{{ randAlphaNum 4 | lower }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tibcohub-recipes.labels" . | nindent 4 }}
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 3600
  template:
    metadata:
      labels:
        {{- include "tibcohub-recipes.labels" . | nindent 8 }}
    spec:
    {{- if .Values.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
    {{- end }}
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: tibcohub
        image: {{ include "tibcohub-recipes.image.registry" .}}{{"/"}}{{ include "tibcohub-recipes.image.repository" .}}{{"/"}}{{ .Values.image.name }}:{{ .Values.image.tag}}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- with .Values.probes.startupProbe }}
        startupProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- if .Values.securityContext }}
        securityContext:
        {{- toYaml .Values.securityContext | nindent 10 }}
        {{- end }}
        {{- if eq (include "tibcohub-recipes.enableResourceConstraints" . ) "true" }}
        resources:
        {{- toYaml .Values.scripts.resources | nindent 10 }}
        {{- end }}
        env:
        - name: CAPABILITY_NAME
          value: "tibcohub"
        - name: RECIPE_MOUNT_LOCATION
          value: "/opt/tibco/recipe"
        - name: RECIPE_TARGET_LOCATION
          value: "/private/tsc/config/capabilities/platform"
        - name: RECIPE_RELEASE_VERSION
          value: "1.14.0"
        - name: SPACE_SEPARATED_UNSUPPORTED_RECIPE_VERSIONS
          value: ""
        - name: OVERWRITE_RECIPE
          value: {{ .Values.capabilities.tibcohub.overwriteRecipe | quote }}
        - name: IS_LATEST
          value: {{ .Values.capabilities.tibcohub.isLatest | quote }}
        volumeMounts:
        - name: {{ include "tibcohub-recipes.consts.appName" . }}-tibcohub-volume
          mountPath: /opt/tibco/recipe
        - name: scripts-config-volume
          mountPath: /opt/tibco/scripts
        - name: store-vol
          mountPath: /private/tsc/config
          subPath: tsc/config
        - name: tmp-vol
          mountPath: /tmp
        command: ["sh"]
        args: ["-c", "/opt/tibco/scripts/run.sh"]
      restartPolicy: Never
      volumes:
        - name: {{ include "tibcohub-recipes.consts.appName" . }}-tibcohub-volume
          configMap:
            name: {{ include "tibcohub-recipes.consts.appName" . }}-tibcohub
        - name: scripts-config-volume
          configMap:
            name: {{ include "tibcohub-recipes.consts.appName" . }}-script
            defaultMode: 0777
        - name: store-vol
          persistentVolumeClaim:
            claimName: {{ include "tibcohub-recipes.pvc-name" . }}
        - emptyDir: {}
          name: tmp-vol
{{- if (include "tibcohub-recipes.container-registry.secret" .) }}
      imagePullSecrets:
        - name: {{ include "tibcohub-recipes.container-registry.secret" . }}
{{- end }}