# Copyright Â© 2023-2026. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.

{{ if eq .Values.global.cp.resources.ingress.ingressController "traefik" -}}
{{- $fullName := include "tibcohub.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Release.Namespace }}-{{ $fullName }}-strip-prefix@kubernetescrd
    {{- with .Values.global.cp.resources.ingress.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  ingressClassName: {{ .Values.global.cp.resources.ingress.ingressClassName }}
  rules:
    - host: {{ .Values.global.cp.resources.ingress.fqdn }}
      http:
        paths:
          - backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ .Values.service.ports.backend }}
            path: {{ .Values.ingress.pathPrefix }}
            pathType: Prefix
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ $fullName }}-strip-prefix
spec:
  stripPrefix:
    prefixes:
      - {{ .Values.ingress.pathPrefix }}
{{- end }}

