# Copyright Â© 2023. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
{{ if eq .Values.publicApi.ingress.controllerName "nginx" -}}
{{ $cpHostname := (.Values.global.cp).cpHostname | required ".Values.global.cp.cpHostname is required." }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "common.names.fullname" . }}-wkc
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: backstage
    {{- include "tibcohub.platform.commonLabels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/upstream-vhost: {{ $cpHostname }}
    nginx.ingress.kubernetes.io/rewrite-target: /.well-known/openid-configuration
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header x-cp-host {{ $cpHostname }};
    {{- with .Values.global.cp.resources.ingress.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.publicApi.ingress.config.className }}
  rules:
    - host: {{ .Values.publicApi.ingress.config.fqdn }}
      http:
        paths:
          - backend:
              service:
                name: {{ include "common.names.fullname" . }}-wkc
                port:
                  number: 443
            path: /tibco/hub/.well-known/openid-configuration
            pathType: Exact
{{- end }}
