#
# Copyright Â© 2023 - 2024. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "o11y-service.consts.appName" . }}
  labels:
    {{- include "o11y-service.shared.labels.standard" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "o11y-service.shared.labels.selector" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        {{- include "o11y-service.shared.labels.standard" . | nindent 8 }}
        networking.platform.tibco.com/kubernetes-api: enable
        egress.networking.platform.tibco.com/internet-all: enable
    spec:
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
      - name: {{ .Values.global.cp.containerRegistry.secret }}
      {{- if .Values.global.cp.resources.serviceaccount.serviceAccountName }}
      serviceAccountName: {{ .Values.global.cp.resources.serviceaccount.serviceAccountName }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: tp-o11y-service
          image: {{ include "o11y-service.image.registry" .}}{{"/"}}{{ include "o11y-service.image.repository" .}}{{"/"}}o11y-service:{{- .Values.global.o11yservice.image.tag | default (include "o11y-service.image.tag" .) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.securityContext }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- end }}
          resources:
            requests:
              cpu: 100m
              memory: 728Mi
            limits:
              cpu: 500m
              memory: 1024Mi
          ports:
            - containerPort: 7820
              name: tp-o11yservice
          env:
            - name: IS_CP
              value: "false"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: DATAPLANE_ID
              value: {{ .Values.global.cp.dataplaneId }}
          volumeMounts:
            - name: o11y-cfgs
              readOnly: true
              mountPath: "/o11y/cfgs"
            - name: o11y-secrets
              readOnly: true
              mountPath: "/o11y/secrets"
{{- if .Values.global.cp.logging.fluentbit.enabled }}
        - name: fluentbit
          image: {{ include "o11y-service.image.registry" .}}{{"/"}}{{ include "o11y-service.image.repository" .}}{{"/"}}fluentbit:{{ .Values.global.cp.logging.fluentbit.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.global.cp.logging.fluentbit.securityContext }}
          securityContext:
            {{- toYaml .Values.global.cp.logging.fluentbit.securityContext | nindent 12 }}
          {{- end }}
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: CONTAINER_NAME
              value: tp-o11y-service
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          volumeMounts:
            - name: podlogs
              mountPath: /var/log/pods
            - name: config-volume
              mountPath: /fluent-bit/etc/
{{- end }}
      volumes:
{{- if .Values.global.cp.logging.fluentbit.enabled }}
        - name: podlogs
          hostPath:
            path: /var/log/pods
            type: Directory
        - name: config-volume
          configMap:
            name: {{ include "o11y-service.consts.appName" . }}-fluentbit-config
{{- end }}
        - name: o11y-cfgs
          configMap:
            name: {{ include "o11y-service.fullname" . }}
        - name: o11y-secrets
          secret:
            secretName: {{ include "o11y-service.fullname" . }}
