#
# Copyright Â© 2023 - 2024. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "o11y-service.fullname" . }}
  labels:
    {{- include "o11y-service.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
stringData:
#logsserver
{{- if eq .Values.global.cp.resources.o11y.logsServer.kind "elasticSearch" }}
  ES_EXPORTER_LOG_INDEX_PASSWORD: {{ quote .Values.global.cp.resources.o11y.logsServer.secret.exporter.userapp.logindex.password }}
  ES_SERVICE_LOG_INDEX_PASSWORD: {{ quote .Values.global.cp.resources.o11y.logsServer.secret.exporter.services.logindex.password }}
  logserver-app-proxy-password: {{ quote .Values.global.cp.resources.o11y.logsServer.secret.proxy.userapp.logindex.password }}
  #'logserver-app-expo-password' duplicate of 'ES_EXPORTER_LOG_INDEX_PASSWORD'
  #logserver-app-expo-password: {{ quote .Values.global.cp.resources.o11y.logsServer.secret.exporter.userapp.logindex.password }}
  #'logserver-svc-expo-password' duplicate of 'ES_SERVICE_LOG_INDEX_PASSWORD'
  #logserver-svc-expo-password: {{ quote .Values.global.cp.resources.o11y.logsServer.secret.exporter.services.logindex.password }}
{{- end }}
#metricsserver
{{- if eq .Values.global.cp.resources.o11y.metricsServer.kind "prometheus" }}
  promserver-proxy-password: {{ quote .Values.global.cp.resources.o11y.metricsServer.secret.proxy.password }}
  promserver-exporter-token: {{ quote .Values.global.cp.resources.o11y.metricsServer.secret.exporter.token }}
{{- end }}
{{- range $key, $value := .Values.global.cp.resources.o11y.logsServer.secret.exporter.userapp.headers }}
  headers-logs-expo-userapp-{{ $key }}: {{ quote $value }}
{{- end }}
  headers-logs-expo-userapp.yaml: |-
{{- toYaml .Values.global.cp.resources.o11y.logsServer.secret.exporter.userapp.headers | nindent 8 }}
{{- range $key, $value := .Values.global.cp.resources.o11y.logsServer.secret.proxy.userapp.headers }}
  headers-logs-proxy-userapp-{{ $key }}: {{ quote $value }}
{{- end }}
  headers-logs-expo-services.yaml: |-
{{- toYaml .Values.global.cp.resources.o11y.logsServer.secret.exporter.services.headers | nindent 8 }}
{{- range $key, $value := .Values.global.cp.resources.o11y.logsServer.secret.exporter.services.headers }}
  headers-logs-expo-services-{{ $key }}: {{ quote $value }}
{{- end }}
{{- range $key, $value := .Values.global.cp.resources.o11y.metricsServer.secret.proxy.headers }}
  headers-metrics-proxy-{{ $key }}: {{ quote $value }}
{{- end }}
{{- range $key, $value := .Values.global.cp.resources.o11y.tracesServer.secret.es.headers }}
  headers-traces-es-{{ $key }}: {{ quote $value }}
{{- end }}
#tracessserver
{{- if eq .Values.global.cp.resources.o11y.tracesServer.kind "jaeger" }}
  jaeger-es-password: {{ quote .Values.global.cp.resources.o11y.tracesServer.secret.es.password }}
{{- end }}