#
# Copyright Â© 2023 - 2024. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "o11y-service.fullname" . }}
  labels:
    {{- include "o11y-service.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- if and (.Values.global.cp.resources.resourcemapping) (eq .Values.global.cp.resources.resourcemapping.O11Y "o11yv3") }}
#------------------------------------------------------------------------
# Multiple exporter O11y Model >= 1.3.0
#------------------------------------------------------------------------
##logexporter:userapp
{{- if .Values.global.cp.resources.o11yv3.logsServer.config.exporter.userApps.enabled }}
{{- if eq .Values.global.cp.resources.o11yv3.logsServer.config.exporter.userApps.kind "elasticSearch" }}
  LOGS_EXPORTER_APP_ES_PASSWORD: {{ quote .Values.global.cp.resources.o11yv3.logsServer.secret.exporter.userApps.elasticSearch.password }}
{{- range $key, $value := .Values.global.cp.resources.o11yv3.logsServer.secret.exporter.userApps.elasticSearch.headers }}
  headers_logs_expo_userapp_{{ $key }}: {{ quote $value }}
{{- end }}
  headers_logs_expo_userapp: |-
{{- toYaml .Values.global.cp.resources.o11yv3.logsServer.secret.exporter.userApps.elasticSearch.headers | nindent 8 }}
{{- end }}
{{- if eq .Values.global.cp.resources.o11yv3.logsServer.config.exporter.userApps.kind "openSearch" }}
  LOGS_EXPORTER_APP_OS_PASSWORD: {{ quote .Values.global.cp.resources.o11yv3.logsServer.secret.exporter.userApps.elasticSearch.password }}
{{- range $key, $value := .Values.global.cp.resources.o11yv3.logsServer.secret.exporter.userApps.elasticSearch.headers }}
  headers_logs_expo_userapp_{{ $key }}: {{ quote $value }}
{{- end }}
  headers_logs_expo_userapp: |-
{{- toYaml .Values.global.cp.resources.o11yv3.logsServer.secret.exporter.userApps.elasticSearch.headers | nindent 8 }}
{{- end }}
{{- if eq .Values.global.cp.resources.o11yv3.logsServer.config.exporter.userApps.kind "kafka" }}
  LOGS_EXPORTER_APP_KAFKA_PASSWORD: {{ quote .Values.global.cp.resources.o11yv3.logsServer.secret.exporter.userApps.kafka.password }}
{{- end }}
{{- end }}
##logproxy:userapp
{{- if .Values.global.cp.resources.o11yv3.logsServer.config.proxy.userApps.enabled }}
{{- if eq .Values.global.cp.resources.o11yv3.logsServer.config.proxy.userApps.kind "elasticSearch" }}
  logserver-proxy-app-password: {{ quote .Values.global.cp.resources.o11yv3.logsServer.secret.proxy.userApps.elasticSearch.password }}
{{- range $key, $value := .Values.global.cp.resources.o11yv3.logsServer.secret.proxy.userApps.elasticSearch.headers }}
  headers-logs-proxy-userapp-{{ $key }}: {{ quote $value }}
{{- end }}
{{- end }}
{{- if eq .Values.global.cp.resources.o11yv3.logsServer.config.proxy.userApps.kind "openSearch" }}
  logserver-proxy-app-password: {{ quote .Values.global.cp.resources.o11yv3.logsServer.secret.proxy.userApps.openSearch.password }}
{{- range $key, $value := .Values.global.cp.resources.o11yv3.logsServer.secret.proxy.userApps.openSearch.headers }}
  headers-logs-proxy-userapp-{{ $key }}: {{ quote $value }}
{{- end }}
{{- end }}
{{- end }}
##logexporter:service
{{- if .Values.global.cp.resources.o11yv3.logsServer.config.exporter.services.enabled }}
{{- if eq .Values.global.cp.resources.o11yv3.logsServer.config.exporter.services.kind "elasticSearch" }}
  LOGS_EXPORTER_SVC_ES_PASSWORD: {{ quote .Values.global.cp.resources.o11yv3.logsServer.secret.exporter.services.elasticSearch.password }}
  headers_logs_expo_services: |-
{{- toYaml .Values.global.cp.resources.o11yv3.logsServer.secret.exporter.services.elasticSearch.headers | nindent 8 }}
{{- range $key, $value := .Values.global.cp.resources.o11yv3.logsServer.secret.exporter.services.elasticSearch.headers }}
  headers_logs_expo_services_{{ $key }}: {{ quote $value }}
{{- end }}
{{- end }}
{{- if eq .Values.global.cp.resources.o11yv3.logsServer.config.exporter.services.kind "openSearch" }}
  LOGS_EXPORTER_SVC_OS_PASSWORD: {{ quote .Values.global.cp.resources.o11yv3.logsServer.secret.exporter.services.openSearch.password }}
  headers_logs_expo_services: |-
{{- toYaml .Values.global.cp.resources.o11yv3.logsServer.secret.exporter.services.openSearch.headers | nindent 8 }}
{{- range $key, $value := .Values.global.cp.resources.o11yv3.logsServer.secret.exporter.services.openSearch.headers }}
  headers_logs_expo_services_{{ $key }}: {{ quote $value }}
{{- end }}
{{- end }}
{{- if eq .Values.global.cp.resources.o11yv3.logsServer.config.exporter.services.kind "kafka" }}
  LOGS_EXPORTER_SVC_KAFKA_PASSWORD: {{ quote .Values.global.cp.resources.o11yv3.logsServer.secret.exporter.services.kafka.password }}
{{- end }}
{{- end }}
##logexporter:auditSafe
{{- if .Values.global.cp.resources.o11yv3.logsServer.config.exporter.auditSafe.enabled }}
{{- if eq .Values.global.cp.resources.o11yv3.logsServer.config.exporter.auditSafe.kind "elasticSearch" }}
  LOGS_EXPORTER_AUDITSAFE_ES_PASSWORD: {{ quote .Values.global.cp.resources.o11yv3.logsServer.secret.exporter.auditSafe.elasticSearch.password }}
{{- end }}
{{- if eq .Values.global.cp.resources.o11yv3.logsServer.config.exporter.auditSafe.kind "openSearch" }}
  LOGS_EXPORTER_AUDITSAFE_OS_PASSWORD: {{ quote .Values.global.cp.resources.o11yv3.logsServer.secret.exporter.auditSafe.elasticSearch.password }}
{{- end }}
{{- range $key, $value := .Values.global.cp.resources.o11yv3.logsServer.secret.exporter.auditSafe.elasticSearch.headers }}
  headers_logs_expo_auditsafe_{{ $key }}: {{ quote $value }}
{{- end }}
  headers_logs_expo_auditsafe: |-
{{- toYaml .Values.global.cp.resources.o11yv3.logsServer.secret.exporter.auditSafe.elasticSearch.headers | nindent 8 }}
{{- end }}

##logproxy:auditSafe
{{- if .Values.global.cp.resources.o11yv3.logsServer.config.proxy.auditSafe.enabled }}
{{- if or (eq .Values.global.cp.resources.o11yv3.logsServer.config.proxy.auditSafe.kind "elasticSearch") (eq .Values.global.cp.resources.o11yv3.logsServer.config.proxy.auditSafe.kind "openSearch")}}
  logserver-proxy-auditsafe-password: {{ quote .Values.global.cp.resources.o11yv3.logsServer.secret.proxy.auditSafe.elasticSearch.password }}
{{- range $key, $value := .Values.global.cp.resources.o11yv3.logsServer.secret.proxy.auditSafe.elasticSearch.headers }}
  headers-logs-proxy-auditsafe-{{ $key }}: {{ quote $value }}
{{- end }}
{{- end }}
{{- end }}
##metricsserver:exporter
{{- if .Values.global.cp.resources.o11yv3.metricsServer.config.exporter.enabled }}
{{- if eq .Values.global.cp.resources.o11yv3.metricsServer.config.exporter.kind "prometheus" }}
  promserver_exporter_password: {{ quote .Values.global.cp.resources.o11yv3.metricsServer.secret.exporter.prometheus.password }}
{{- range $key, $value := .Values.global.cp.resources.o11yv3.metricsServer.secret.exporter.prometheus.headers }}
  headers_metrics_exporter_{{ $key }}: {{ quote $value }}
{{- end }}
{{- end }}
{{- if eq .Values.global.cp.resources.o11yv3.metricsServer.config.exporter.kind "kafka" }}
  METRICS_EXPORTER_KAFKA_PASSWORD: {{ quote .Values.global.cp.resources.o11yv3.metricsServer.secret.exporter.kafka.password }}
{{- end }}
{{- end }}
##metricsserver:proxy
{{- if .Values.global.cp.resources.o11yv3.metricsServer.config.proxy.enabled }}
{{- if eq .Values.global.cp.resources.o11yv3.metricsServer.config.proxy.kind "prometheus" }}
  {{- if .Values.global.cp.resources.o11yv3.metricsServer.secret.proxy.prometheus.password }}
  promserver-proxy-password: {{ quote .Values.global.cp.resources.o11yv3.metricsServer.secret.proxy.prometheus.password }}
  {{- end }}
{{- range $key, $value := .Values.global.cp.resources.o11yv3.metricsServer.secret.proxy.prometheus.headers }}
  headers-metrics-proxy-{{ $key }}: {{ quote $value }}
{{- end }}
{{- end }}
{{- end }}
##tracessserver:exporter
{{- if .Values.global.cp.resources.o11yv3.tracesServer.config.exporter.enabled }}
{{- if eq .Values.global.cp.resources.o11yv3.tracesServer.config.exporter.kind "elasticSearch" }}
{{- range $key, $value := .Values.global.cp.resources.o11yv3.tracesServer.secret.exporter.elasticSearch.headers }}
  headers_traces_exporter_es_{{ $key }}: {{ quote $value }}
{{- end }}
  jaeger_es_exporter_password: {{ quote .Values.global.cp.resources.o11yv3.tracesServer.secret.exporter.elasticSearch.password }}
{{- end }}
{{- if eq .Values.global.cp.resources.o11yv3.tracesServer.config.exporter.kind "openSearch" }}
{{- range $key, $value := .Values.global.cp.resources.o11yv3.tracesServer.secret.exporter.openSearch.headers }}
  headers_traces_exporter_os_{{ $key }}: {{ quote $value }}
{{- end }}
  jaeger_os_exporter_password: {{ quote .Values.global.cp.resources.o11yv3.tracesServer.secret.exporter.openSearch.password }}
{{- end }}
{{- if eq .Values.global.cp.resources.o11yv3.tracesServer.config.exporter.kind "kafka" }}
  TRACES_EXPORTER_KAFKA_PASSWORD: {{ quote .Values.global.cp.resources.o11yv3.tracesServer.secret.exporter.kafka.password }}
{{- end }}
{{- end }}
##tracessserver:proxy
{{- if .Values.global.cp.resources.o11yv3.tracesServer.config.proxy.enabled }}
{{- if eq .Values.global.cp.resources.o11yv3.tracesServer.config.proxy.kind "elasticSearch" }}
{{- range $key, $value := .Values.global.cp.resources.o11yv3.tracesServer.secret.proxy.elasticSearch.headers }}
  headers-traces-es-{{ $key }}: {{ quote $value }}
{{- end }}
  jaeger-es-password: {{ quote .Values.global.cp.resources.o11yv3.tracesServer.secret.proxy.elasticSearch.password }}
{{- end }}
{{- if eq .Values.global.cp.resources.o11yv3.tracesServer.config.proxy.kind "openSearch" }}
{{- range $key, $value := .Values.global.cp.resources.o11yv3.tracesServer.secret.proxy.openSearch.headers }}
  headers-traces-es-{{ $key }}: {{ quote $value }}
{{- end }}
  jaeger-es-password: {{ quote .Values.global.cp.resources.o11yv3.tracesServer.secret.proxy.openSearch.password }}
{{- end }}
{{- end }}
{{- else }}
#------------------------------------------------------------------------
# Exporter O11y Model <= 1.2.0. DO NOT MODIFY THE BELOW
#------------------------------------------------------------------------
#logsserver
{{- if eq .Values.global.cp.resources.o11y.logsServer.kind "elasticSearch" }}
  ES_EXPORTER_LOG_INDEX_PASSWORD: {{ quote .Values.global.cp.resources.o11y.logsServer.secret.exporter.userapp.logindex.password }}
  ES_SERVICE_LOG_INDEX_PASSWORD: {{ quote .Values.global.cp.resources.o11y.logsServer.secret.exporter.services.logindex.password }}
  logserver-proxy-app-password: {{ quote .Values.global.cp.resources.o11y.logsServer.secret.proxy.userapp.logindex.password }}
  #'logserver-app-expo-password' duplicate of 'ES_EXPORTER_LOG_INDEX_PASSWORD'
  #logserver-app-expo-password: {{ quote .Values.global.cp.resources.o11y.logsServer.secret.exporter.userapp.logindex.password }}
  #'logserver-svc-expo-password' duplicate of 'ES_SERVICE_LOG_INDEX_PASSWORD'
  #logserver-svc-expo-password: {{ quote .Values.global.cp.resources.o11y.logsServer.secret.exporter.services.logindex.password }}
{{- end }}
#metricsserver
{{- if eq .Values.global.cp.resources.o11y.metricsServer.kind "prometheus" }}
  promserver-proxy-password: {{ quote .Values.global.cp.resources.o11y.metricsServer.secret.proxy.password }}
  promserver-exporter-token: {{ quote .Values.global.cp.resources.o11y.metricsServer.secret.proxy.token }}
{{- end }}
{{- range $key, $value := .Values.global.cp.resources.o11y.logsServer.secret.exporter.userapp.headers }}
  headers-logs-expo-userapp-{{ $key }}: {{ quote $value }}
{{- end }}
  headers-logs-expo-userapp.yaml: |-
{{- toYaml .Values.global.cp.resources.o11y.logsServer.secret.exporter.userapp.headers | nindent 8 }}
{{- range $key, $value := .Values.global.cp.resources.o11y.logsServer.secret.proxy.userapp.headers }}
  headers-logs-proxy-userapp-{{ $key }}: {{ quote $value }}
{{- end }}
  headers-logs-expo-services.yaml: |-
{{- toYaml .Values.global.cp.resources.o11y.logsServer.secret.exporter.services.headers | nindent 8 }}
{{- range $key, $value := .Values.global.cp.resources.o11y.logsServer.secret.exporter.services.headers }}
  headers-logs-expo-services-{{ $key }}: {{ quote $value }}
{{- end }}
{{- range $key, $value := .Values.global.cp.resources.o11y.metricsServer.secret.proxy.headers }}
  headers-metrics-proxy-{{ $key }}: {{ quote $value }}
{{- end }}
{{- range $key, $value := .Values.global.cp.resources.o11y.tracesServer.secret.es.headers }}
  headers-traces-es-{{ $key }}: {{ quote $value }}
{{- end }}
#tracessserver
{{- if eq .Values.global.cp.resources.o11y.tracesServer.kind "jaeger" }}
  jaeger-es-password: {{ quote .Values.global.cp.resources.o11y.tracesServer.secret.es.password }}
{{- end }}
{{- end }}
