# Copyright Â© 2026. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#
apiVersion: v2
name: tibco-cp-bw
version: 1.15.0-alpha.49
appVersion: 1.15.0
description: TIBCO Controlplane chart for BW Capability
dependencies:
  - name: bw-recipes
    version: "1.15.*"
    condition: bw-recipes.enabled
  - name: bw-webserver
    version: "1.15.*"
    condition: bw-webserver.enabled
  - name: bwce-utilities
    version: "1.15.*"
    condition: bwce-utilities.enabled
  - name: bw5ce-utilities
    version: "1.15.*"
    condition: bw5ce-utilities.enabled
