#
# Copyright (c) 2023-2026. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#

apiVersion: v2
appVersion: "10.5.0-39"
description: A Helm chart for deploying msg-gateway in K8DPs
keywords:
- tp-msg-gateway
name: msg-gateway-tp
version: "1.15.31"
