# CP common setting
global:
  cp:
    dpUrl:
      host: "dp-{{ $.Values.global.cp.dataplaneId }}.platform.local"
      port: 443
    dataplane:
      hostCloudType: "unset"
    dataplaneId: "xx123"
    containerRegistry:
      registry: "ghcr.io"
      repository: "tibco/msg-platform-cicd"
      secret: "cic2-tcm-ghcr-secret"
      pullSecret: "cic2-tcm-ghcr-secret"
      pullPolicy: ""
    resources:
      serviceaccount:
        serviceAccountName: "provisioner"
    logging:
      fluentbit:
        enabled: true

# Message Gateway additional settings
msggw:
  basename: ""
  image: ""
dp:
  pullSecret: ""
  registry: ""
  repo: ""
  pullPolicy: ""
  serviceAccount: ""
# Support EMS values files
ems:
  msgData: {}
