#
# Copyright Â© 2023 - 2024. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#

apiVersion: v1
appVersion: 1.21.2
description: Helm chart for istio control plane
icon: https://github.com/cncf/artwork/blob/master/projects/istio/icon/color/istio-icon-color.svg
keywords:
- istio
- istiod
- istio-discovery
name: istio-istiod
sources:
- https://github.com/istio/istio
version: 1.2.11
