#
# Copyright (c) 2023-2026. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#

#
# HELPER VARIABLE DEFINITIONS
{{- $params := include "need.msg.gateway.params" . | fromYaml -}}
{{- $basename := printf "%s" $params.msggw.basename  -}}
{{- $svcname := $basename -}}
#
{{- if $params.enableIngress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ $basename }}-ops"
  namespace: {{ .Release.Namespace }}
  annotations:
    ingress.kubernetes.io/path-rewrite: '/tibco/agent/msg/ops/shell/toolset/(.*) /\1'
  labels:
    {{- include "msg-gateway.std.labels" $params | nindent 4 }}
    app.kubernetes.io/component: msg-gateway-ingress
spec:
  ingressClassName: "tibco-dp-{{ $params.dp.name }}"
  rules:
  - host: {{ include "msg.dp.dpUrl.host" . }}
    http:
      paths:
      - pathType: Prefix
        path: /tibco/agent/msg/ops/shell/toolset/
        backend:
          service:
            name: "{{ $svcname}}"
            port:
              number: {{ int $params.msggw.ports.gatewayApiPort | default 8376 }}
  - host: "{{ .Values.global.cp.cpHostname | default "sub.cp.platform.local" }}"
    http:
      paths:
      - pathType: Prefix
        path: /tibco/agent/msg/ops/shell/toolset/
        backend:
          service:
            name: "{{ $svcname}}"
            port:
              number: {{ int $params.msggw.ports.gatewayApiPort | default 8376 }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ $basename }}-api"
  namespace: {{ .Release.Namespace }}
  annotations:
    ingress.kubernetes.io/path-rewrite: '/tibco/agent/msg/ct/toolset/(.*) /\1'
  labels:
    {{- include "msg-gateway.std.labels" $params | nindent 4 }}
    app.kubernetes.io/component: msg-gateway-ingress
spec:
  ingressClassName: "tibco-dp-{{ $params.dp.name }}"
  rules:
  - host: {{ include "msg.dp.dpUrl.host" . }}
    http:
      paths:
      - pathType: Prefix
        path: /tibco/agent/msg/ct/toolset/
        backend:
          service:
            name: "{{ $svcname}}"
            port:
              number: {{ int $params.msggw.ports.gatewayApiPort | default 8376 }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ $basename }}-restd"
  namespace: {{ .Release.Namespace }}
  annotations:
    ingress.kubernetes.io/path-rewrite: '/tibco/agent/msg/ct/restd/(.*) /\1'
  labels:
    {{- include "msg-gateway.std.labels" $params | nindent 4 }}
    app.kubernetes.io/component: msg-gateway-ingress
spec:
  ingressClassName: "tibco-dp-{{ $params.dp.name }}"
  rules:
  - host: {{ include "msg.dp.dpUrl.host" . }}
    http:
      paths:
      - pathType: Prefix
        path: /tibco/agent/msg/ct/restd/
        backend:
          service:
            name: "{{ $svcname}}"
            port:
              # FIXME: Values setting
              number: 9014

{{- end }}
