#
#
# Copyright Â© 2023 - 2025. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#

#
{{ if .Values.apm.ingress.enabled -}}
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-apm
  namespace: {{ .Release.Namespace }}
  {{- with .Values.apm.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.apm.ingress.ingressClassName }}
  rules:
    - host: {{ .Values.apm.ingress.host }}.{{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.apm.ingress.service }}
                port:
                  name: https
{{- end -}}
