#
#
# Copyright Â© 2023 - 2024. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#

#
{{ if .Values.storage.enabled -}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{.Values.storage.name }}
  namespace: {{ .Release.Namespace }}
provisioner: ebs.csi.aws.com
allowVolumeExpansion: true 
reclaimPolicy: {{.Values.storage.reclaimPolicy}}
volumeBindingMode: WaitForFirstConsumer
parameters:
  fsType: ext4
  type: gp3
  encrypted: "true"
{{- end -}}
