# Copyright Â© 2024. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#
apiVersion: v2
name: tp-cp-flogo-recipes
description: TIBCO Platform Flogo Data Plane recipes
type: application
version: 1.3.31
appVersion: "1.3.0-HF1"
keywords:
  - tibco-platform
  - control-plane
annotations:
  app.helm.sh/component: control-plane
  app.helm.sh/name: tp-cp-flogo-recipes
